http-rs/tide

src/body.rs

This makes it clear that there is no streaming going on, since deserializing a stream of bytes without first buffering into Vec\<u8\> is when you would typically see serde_json::from_reader come up.

Use serde_json::from_slice to deserialize from &[u8]

---

Cargo.toml
examples/graphql.rs

This PR adds a simple yet functional GraphQL server example powered by Juniper. The server has an accumulator that can add values.
This is somewhat boring, but I think this is a good place to start.

Add simple GraphQL example

---

examples/default_headers.rs
src/lib.rs
src/middleware/default_headers.rs
src/middleware/mod.rs

PR is to add the ability to create default headers for every request. This is more or less taken from actix-web!
I am also trying to add the method `headers` which lets you specify a Vec of headers, e.g.
```rust
let mut app = tide::App::new(());
app.middleware(
DefaultHeaders::new()
.headers(vec!(
["X-Version", "1.0.0"],
["X-Server", "Tide"]
))
);
```
As opposed to:
```rust
let mut app = tide::App::new(());
app.middleware(
DefaultHeaders::new()
.header("X-Version", "1.0.0")
.header("X-Server", "Tide")
);
```
Not sure which one is more clear? Currently the latter is what is implemented. If it's decided that the other way is better, I can work on implementing it.

Feature: Default Headers Middleware

---

Cargo.toml
examples/body_types.rs
src/body.rs

An attempt at resolving #22, this seemed almost too easy, so maybe I'm misunderstanding something here 😅
This makes it possible extract `x-www-form-urlencoded` data from the request body via [serde_qs](https://crates.io/crates/serde_qs). 
This means that even nested fields can be extracted via the same `foo[bar]` syntax used in node's qs and Ruby on Rails. This is somewhat of an opinionated decision, but the web ecosystem seems to be converging on this and it is a huge boon when submitting complex form data.
The alternative is only allowing a flat map of key->values but this is very limiting.
Another decision here is the naming of the extractor. Since there are two different form encodings, `application/x-www-form-urlencoded` and `multipart/form-data`<sup>1</sup> it might seem reasonable …

Add form data extraction from body via serde_qs

---

Cargo.toml
examples/multipart-form/main.rs
examples/multipart-form/test.txt
src/body.rs
src/head.rs

Hi there, not at all an expert here but I would like to try help a bit if I can.
Do you think either one of the two methods I provided here could be a good way of handling multipart form file-upload? 
(I used some idea from here: https://github.com/rust-net-web/tide/pull/44)
The differences between the two methods I mentioned here are: (see the example first)
* `form_auto` use a new body type created in `body::MultipartFile` to allow user of tide easier get a `Vec<u8>` of the file uploaded.
* `form_manual` use a new head type `head::NamedHeader` to allow user get header "content-type" and raw body as `Vec<u8>` then manually use the `multipart` crate method to get what he want. 
Not sure whether I am heading the correct direction here but I would like to hear your opinion. I am kind of new …

Allow handle file upload via multipart form

---

src/app.rs
src/middleware/default_headers.rs
src/middleware/mod.rs

Side effect: `Request` and `Response` will be given by reference.

Relieve middleware FutureObj lifetime bounds

---

examples/simple_nested_router.rs
src/app.rs
src/lib.rs
src/router.rs
src/url_table.rs

Here is the new design, taking ideas of @aturon from #43. An implementation of #4. (Resolves #4)
* Subrouter support is implemented in `router::Router`, using `router::ResourceHandle`.
* Only middlewares **before** the call of `Router::at()` will be applied to the path (resources and subrouters.)
---

Subrouters and per-endpoint middleware

---

.travis.yml
Cargo.toml
path_table/Cargo.toml
path_table/src/lib.rs
src/lib.rs
src/router.rs

Resolves #2.
Renamed `url_table` to `path_table` as "URL" feels like a broader term than "path" (which the crate is actually dealing with).

Extract `url_table` into `path_table` crate

---

.travis.yml

Todays nightly has a [bug that breaks the builds](https://travis-ci.org/hoodie/tide/builds/459748501). but it [seems to build](https://travis-ci.org/hoodie/tide/builds/459753610) with the version from November 24th

Pin a specific nightly version for travis builds

---

Cargo.toml
examples/computed_values.rs
src/lib.rs
src/request.rs

This adds an example for how to use computed values. We had to make the
Compute trait public for that.

Expose Computed Values Api

---

Cargo.toml
examples/computed_values.rs

This extends the cookie example to handle multiple cookies.

Extend cookie example

---

src/app.rs
src/router.rs

I took a first stab at #18.
Some items for discussion:
- I suggest we consistently use one of the terms "component" or "segment" for the "/"-separated parts of a URL path; currently both are used in `lib.rs` and other places; Akka HTTP uses "segment" which I also prefer
- ~The doc fist test (around line 33) fails: "help: add #![feature(async_await)] to the crate attributes to enable"; but these are enabled, what to do?~
- How can I refer from one `at` method (in "app.rs") to another one (in "router.rs")? Is the way I did it correct?

Document routing syntax

---

examples/body_types.rs
examples/graphql.rs
examples/messages.rs
examples/multipart-form/main.rs
src/body.rs
src/head.rs

The following body types are covered:
- Str
- StrLossy
- Bytes
- Form
- MuliypartForm
- Json
And some types from head.rs:
- Path
- Named
Are all the cases covered? I'm actually not sure about Named, too.

Implemented Deref for body types and some Path types, updated examples

---

examples/default_handler.rs
path_table/src/lib.rs
src/app.rs
src/body.rs
src/endpoint.rs
src/extract.rs
src/head.rs
src/middleware/mod.rs
src/request.rs
src/router.rs

So this should tackle #10 .
Little bit of info on what is happening here,
The call to router will no longer return `Some(RouteResult)` and instead always returns a `RouteResult`. The router will fallback to the `default_handler` that is set. This allows us to use all middleware that are set in the `middleware_base` of the root router. In the example, you can try it and see that logging is now working for the fallback route.
I'm not going to lie, this particular PR was probably a bit above my Rust level and feels a bit hacky to me. Let me know what you guys think!
Also, special thank you to @tirr-c for his countless hours answering my non-stop questions ❤️ 
TODO:
I'd like to write some tests but I will wait until the final implementation to do so. Let's hold off on merging this at least …

Default Handler Implementation

---

examples/named_path.rs
examples/simple_nested_router.rs
path_table/src/lib.rs
src/head.rs
src/router.rs

I know that naming is hard, but I nevertheless give it a try: Like asked in #76 I suggest to consistently use either of the terms "component" or "segment" for the "/"-separated parts of the path of a URL. Currently both terms are mixed in lib.rs and other places. I suggest to use "segment" which I think is more specific in the context of a path than "component".

Rename path component to path segment

---

Cargo.toml

By default, `multipart` will be built with a bunch of default features that Tide doesn't really use. This PR turns off any unused features in order to boost the initial build time.

Enable only needed features for `multipart`

---

examples/catch_all.rs
path_table/src/lib.rs
src/router.rs

This PR adds the concept of "wildcard modifers". Only one modifier is implemented for now: `*`, the zero-or-more modifier. It matches zero or more path segments. For example, `/static/{path}*` matches `/static/foo.txt`, `/static/images/bar.jpg`, and `/static`. `path` will be `"foo.txt"`, `"bar.jpg"`, and `""`, respectively.
* `{}*` can be written as `*`.
* Since this "catch-all" is still a wildcard, concrete segments take precedence. With `/static/foo/bar` and `/static/*`, `/static/foo` will **fail to route**. We might need to solve this problem (#12).

Implement "catch-all" endpoint

---

Cargo.toml
src/lib.rs

Update `futures-preview` and `pin-utils` to match new `Pin` APIs.
Previously, build was failing on the latest nightly due to the change of API.

Update futures-preview and pin-utils

---

examples/default_handler.rs
src/response.rs

This PR adds a provided method, `with_status`, to `IntoResponse`. This method returns a wrapper around the value that modifies response status code.
Part of #116. This change makes returning `Json` error easier.
I'm not sure if this is the right direction, though.
I've added a unit test that runs `with_status` on `&'static str`, then compares the final status code.

Add status code modifier for IntoResponse

---

examples/graphql.rs
src/body.rs
src/response.rs

Remove `'static` bound from `IntoResponse`.
We don't need to *require* `IntoResponse` to be `'static`. Even if the value is not `'static`, most of the time we'll going to build a response in the same way as `'static` ones. If it doesn't work for some type, we can add `'static` bound to the `impl` block.
All existing tests passed.

Relieve lifetime bound of IntoResponse

---

examples/messages.rs
src/app.rs
src/endpoint.rs

I've noticed that some doctests and one example have a pattern where a `fn new()` is defined for `Database` that basically does nothing except call `::new()` on all members. This is essentially the same as what the `Default` trait does, so this PR proposes to use that instead in the interest of having shorter and more idiomatic examples.
This PR changes two doctests (one in `app.rs` and one in `endpoint.rs`) as well as the example `messages.rs` to derive and use `Default::default()` for making a new empty Database instead of defining a `fn new()` in an inherent impl block and using that.
This PR is not strictly required, since it doesn't fix any technical problems.
It only serves to make the doctests and examples a little more concise,
allowing potential readers to focus on the parts that …

Clean up doctests and messages example via Default trait

---

.github/CONTRIBUTING.md

Some links in the contribution documentation were broken due to switched up style of brackets (`[]` instead of `()`)
Fixes #127

Fix links to `Code of Conduct`

---

src/configuration/mod.rs

Makes the Environment struct publicly available.
I noticed the Environment struct is required in some APIs, but wasn't publicly available.
Works locally

make the Environment struct public

---

src/app.rs

**docs: updated docs to have correct default port**
change `7878` to `8181` which is the default port
set in [`src/configuration/default_config.rs`](https://github.com/rust-net-web/tide/blob/master/src/configuration/default_config.rs#L31)
Update documentation.

docs: updated docs to have correct default port

---

.travis.yml
Cargo.toml
src/app.rs
src/body.rs
src/lib.rs
src/request.rs
src/response.rs
src/router.rs
src/serve.rs

This PR refactors Tide to internally use the new [http-service crate](https://github.com/rust-net-web/http-service). That crate provides an `HttpService` trait, meant to provide a Rack-like interface between low-level http servers (like hyper) and frameworks or applications that sit on top of them.
The refactoring isolates all hyper-specific shim code to a new module, `serve`, which presents an `HttpService`-based interface to the rest of the crate. Eventually this shim code should be moved into an external crate.
The ultimate goals here are:
- To move the shim code to work with hyper into a separate crate
- To support a standardized layering such that the base web server can easily be switched out (in Tide and other web frameworks)
As a pure refactoring, no new tests are added.

Refactor to use HttpService internally

---

README.md

Note that the CSS on them is still broken, pending a merge of https://github.com/rustasync/team/pull/93 (or an alternative fix for https://github.com/rustasync/team/issues/92)

Update blog post URLs after wg-net repo move

---

README.md

Looks like the CI badge was broken when the repository was moved from the `rust-net-web` to the `rustasync` org.

Update the CI badge to point to rustasync/tide

---

Cargo.toml
tests/wildcard.rs

This solves [ust-net-web/tide#15](https://github.com/rust-net-web/tide/issues/15). We wanted to extract the `HttpBackend` inside the tests, and offer it inside the `http-service` create (https://github.com/rust-net-web/http-service/pull/6).
I removed the `HttpBackend` from the `wildcard.rs` tests, and used the external crate (which needs to be merged and pushed first inside `http-service`).
After the change, we are able to offer a TestBackend which is not tied to `Tide`.
The PR in `http-service` needs to be merged first. I tested it locally and it ran fine.

Add external crate http_service_mock, delete local TestBackend

---

.travis.yml
tests/wildcard.rs

This fixes CI breakage.
EDIT: Versions from `nightly-2019-03-03` cause ICE on tests. Rolled back to the latest version that works well.

Update to nightly-2019-02-27 and make it default

---

examples/catch_all.rs

This PR removes the asterisk from the `catch_all` route params, resolving the issue raised in #167.

example: remove asterisk from catch_all route params

---

examples/catch_all.rs

c70d2bc resolved the panic raised in the issue, but it also exposed my
ignorance with regards to route-recognizer, our new routing library.
Placing the `*` after a named param, as it was in the original example,
leads to the behavior mentioned in #167. route-recognizer is operating
exactly as intended. `:path*` doesn't capture additional URL segments,
where `*path` does. (It also appends `*` to the parameter key, as well.)

fix: Capture wildcard path correctly, resolve #167.

---

src/lib.rs

I added `pub use http;` in `lib.rs`
Since `tide` heavily depends on `http` crate, it would be great if we can use `http` crate without adding to `Cargo.toml`.
I checked via `cargo doc` that the `http` crate is re-exported.

Re-export http crate

---

src/endpoint.rs

Adds an example of a Tide endpoint that does not make use of `async`
Resolves https://github.com/rustasync/tide/issues/19
The docs should build correctly.

Documents acceptable endpoint fns

---

.travis.yml
Cargo.toml
src/endpoint.rs
src/error.rs
src/lib.rs

Sync up the new changes in the nightly futures_api: futures dependency to 0.3.0-alpha.14
Also, updated all patch versions of other deps, while at it.
Blocker for successful build/release: https://github.com/rustasync/http-service/pull/14

fix: sync up with nightly futures_api

---

README.md

Closes https://github.com/rustasync/tide/issues/173
Update docs to include supported rust versions
https://github.com/rustasync/tide/issues/173
N/A

docs: add supported rust versions

---

Cargo.toml
examples/body_types.rs
examples/messages.rs
examples/multipart-form/main.rs

To enhance compatibility with Rust 2018, Serde now supports a feature, `derive`, which includes `serde_derive` macros automatically.
Updates Tide imports for Serde to match Rust 2018 style.
It builds, including examples, and all existing tests pass. (Including on #175, where this change was originally raised.)

Use Rust 2018 imports for Serde

---

Cargo.toml
src/lib.rs
src/querystring.rs

This commit adds query string extraction via the `ExtractQuery` trait, implemented for `tide::Context`.
Added a module, `querystring`, which includes the `ExtractQuery` trait to help with validating and deserializing HTTP query parameters.
Processing query parameters is a common concern of most HTTP frameworks.
Simulated requests to a Tide endpoint. This PR doesn't remove or alter existing functionality.

Add query string extension trait

---

Cargo.toml
src/forms.rs

As mentioned in #175, `serde_qs` isn't nearly as well maintained as `serde_urlencoded`. The only difference between the two libraries is the former's support for nested fields (a feature we can implement if need be).
So we don't have two different libraries doing nearly the same thing, I think it makes sense to use `serde_urlencoded` in forms if we're also using it for query string extraction (#175). 
Substitute `serde_urlencoded` for `serde_qs`. For uses contained in this PR, the API is identical. 
Push Tide towards a single library for handling serialization of URL-encoded data.
Existing tests pass, and the `multipart-form` example was evaluated.

Migrate to serde_urlencoded, and away from serde_qs

---

.travis.yml
Cargo.toml
examples/body_types.rs
examples/catch_all.rs
examples/cookies.rs
examples/graphql.rs
examples/messages.rs
examples/multipart-form/main.rs
src/app.rs
src/endpoint.rs
src/error.rs
src/forms.rs
src/lib.rs
src/middleware/cookies.rs
src/middleware/default_headers.rs
src/middleware/logger.rs
src/middleware/mod.rs
src/router.rs
tests/wildcard.rs

Remove FutureObj usage and futures_api feature
Blocked on an http-service release with https://github.com/rustasync/http-service/pull/23

Update for futures v0.3.0-alpha.15

---

rfcs/000-template.md

This adds an RFC template to Tide, similar to [rustwasm's RFC template](https://github.com/rustwasm/rfcs).
When making changes to an API it can be useful to get consensus on the design first in a structured manner before moving to implementation. The Rust project has proven that filing RFCs has been a a good strategy to discuss these kinds of changes, and we're seeing a similar process work well for [`rustwasm/gloo`](https://github.com/rustwasm/gloo/pull/76) and [`crossbeam`](https://github.com/crossbeam-rs/rfcs/tree/master/text).
I've chosen to add the RFC template directly to Tide so we can discuss changes in the same repo. Having a separate RFC directory could be another option, but I feel that could be something we can  move to at a later stage if we think that's desirable. The main …

add rfc template

---

rfcs/001-app-new.md

[rendered](https://github.com/rustasync/tide/blob/rfc-app-new/rfcs/001-app-new.md)
This proposes changes to the `App` constructor, and renaming `AppData` to `State`.
Also in general keen to hear if this process works for people; my hope is that by starting by introducing RFCs for API changes we can split discussions about the problem space from discussions the implementation details.
Continuation of https://github.com/rustasync/tide/pull/189

app constructor RFC

---

README.md
examples/body_types.rs
examples/catch_all.rs
examples/cookies.rs
examples/default_headers.rs
examples/graphql.rs
examples/hello.rs
examples/messages.rs
examples/multipart-form/main.rs
src/app.rs
src/context.rs
src/cookies.rs
src/endpoint.rs
src/forms.rs
src/middleware/cookies.rs
src/middleware/mod.rs
src/querystring.rs
src/route.rs
src/router.rs
tests/wildcard.rs

Change App constructor
close: https://github.com/rustasync/tide/issues/190
- Change type name of App structure to State
- Implement App::with_state constructor
- Change App::new(()) to App::new()
- Fixed the part that is 'App :: new (())'
The changes not related to this PR are also included
- Remove unnecessary line  546a223
- Formatting README ab3b2d7
Open another PR for modification of the generics argument 'AppData' (change to State)
See https://github.com/rustasync/tide/blob/master/rfcs/001-app-new.md 
Run ```cargo build``` and ```cargo test```.
There seems to be no problem because the example code works.

Change App constructor

---

.travis.yml
Cargo.toml
examples/body_types.rs
examples/graphql.rs
examples/messages.rs
examples/multipart-form/main.rs
src/app.rs
src/context.rs
src/endpoint.rs
src/forms.rs
src/lib.rs
src/middleware/cookies.rs
src/middleware/default_headers.rs
src/middleware/logger.rs

`await` syntax was implemented in https://github.com/rust-lang/rust/pull/60586, and nightly-2019-05-09 has been released with the changes. Also, `await!` macro will be removed in the future.
Then, futures 0.3.0-alpha.16 was released.
Refs: [migration tool](https://github.com/taiki-e/replace-await)
With this change, the minimum required version will go up to nightly-2019-05-09.

[WIP] Update futures-preview to 0.3.0-alpha.16

---

examples/body_types.rs
examples/cookies.rs
examples/messages.rs
examples/multipart-form/main.rs
src/app.rs
src/context.rs
src/error.rs
src/lib.rs
src/middleware/cookies.rs
src/middleware/default_headers.rs
src/middleware/logger.rs
src/middleware/mod.rs
src/response.rs
src/route.rs
src/router.rs

- Add missing `Debug` impls
- Enforce `missing_debug_implementations`
- Add `#[allow(missing_debug_implementations)]` currently, in places where Debug impls may not apply, or ones which probably need a proper manual Debug impl in the future
`Debug` impl is often required by base cases in Rust (say `Result` for `unwrap`/`unwrap_err`) Currently the lack of `Debug` impl on structs like `Error` ends up causing difficultly in usage.  This lint makes sure we avoid it in the future.

add strict debug impl requirements

---

examples/cookies.rs
src/cookies.rs
src/middleware/cookies.rs
src/querystring.rs

As discussed in #187, functionality of extension traits be identifiable by import path, and the trait itself should be named after the type it extends.
To satisfy those constraints, `querystring::ExtractQuery` becomes `querystring::ContextExt`. Similarly, `cookies::CookiesExt` is now `cookies::ContextExt`. 
Ideally, these changes will land before #162.
To align with Rust best practices and the direction of current project discussions.
Current tests pass after being modified to import new types.

Rename extension traits for Cookies and QueryString

---

README.md
examples/src/body_types.rs
examples/src/catch_all.rs
examples/src/cookies.rs
examples/src/default_headers.rs
examples/src/graphql.rs
examples/src/hello.rs
examples/src/messages.rs
examples/src/multipart_form/mod.rs
examples/src/staticfile.rs
tide/src/app.rs
tide/src/endpoint.rs

* Rename original `serve` to `run`.
* Add `App::serve` that returns a `Future`.
This provides flexibility when composing app server with other futures. (cc #163)
No new tests, existing tests pass.

Rename `serve` to `run`, add asynchronous `serve`

---

examples/src/body_types.rs
examples/src/cookies.rs
examples/src/messages.rs
examples/src/multipart_form/mod.rs
tide/src/middleware/cookies.rs

Fixed by https://github.com/rust-lang/rust/pull/60535 and https://github.com/rust-lang/rust/pull/60676.

Remove #[allow(unused_mut)]

---

.travis.yml
Cargo.toml
tide-compression/Cargo.toml
tide-compression/README.md
tide-compression/examples/simple.rs
tide-compression/src/lib.rs
tide/src/context.rs

Provides compression middleware for outgoing HTTP responses and decompression middleware for incoming HTTP requests.
These two middlewares do the following:
* Automatically handle incoming request decompression for `Content-Encoding` headers that contain one or more applications of `gzip`, `deflate`, `br`, or `zstd`.
* Encode outgoing responses with preferred encoding behavior for any incoming request with a valid `Accept-Encoding` header.
* Allow one to define compression levels for each compression algorithm available.
The decompression middleware actually depends on getting a mutable handle on the request from the context, hence why a new function was added [here](https://github.com/rustasync/tide/blob/b6bcbde42007bf3e2a7c45b38309431c0a918971/src/context.rs#L59-L61).
This closes …

Middleware-based compression and decompression

---

.travis.yml
tide-compression/src/lib.rs
tide-cookies/src/middleware.rs

* Separate out individual build jobs for faster wall-clock testing
* Fix clippy not actually denying warnings (excluded examples because these are currently failing and have non-trivial fixes, https://github.com/rustasync/tide/issues/230)
* Add build job that checks --no-default-features works
* Add build job that checks for intra-doc-resolution failures (excluded tide because of bugs in re-exports with the intra-doc feature, https://github.com/rust-lang/rust/issues/60883)
(based on top of #220, [relevant changes](https://github.com/rustasync/tide/compare/wafflespeanut:code-split..Nemo157:update-travis))
Fixes #226, improves feedback speed on PRs, keeps code quality high
In Travis

Update travis configuration

---

tide-core/src/error.rs

Add `error::ResultDynErrExt`, which provide the same set of methods in `error::ResultErr` for `Result<T, Box<dyn Error>>`.
Trying to resolve issue #208. With this PR, a `e: Result<T, Box<dyn Error>>` can call `e.client_err()`, `e.server_err()` conveniently.
This introduces duplicate codes with `error::ResultErr`. But I did not figure out a way to avoid that.
Not tested - mostly just copy and paste `error::ResultErr`, which does not have a test case for now.
I have no problem adding a unit test if necessary.

Add error::ResultDynErrExt

---

examples/src/body_types.rs
examples/src/multipart_form/mod.rs
tide/src/forms.rs

As follows https://github.com/rustasync/tide/issues/187

Rename trait ExtractForms to ContextExt

---

.travis.yml

Use [`cargo-sweep`](https://github.com/holmgr/cargo-sweep) along with [`-Zmtime-on-use`](https://github.com/rust-lang/cargo/pull/6573) for removing unused data from the Travis cache.
`cargo-sweep` will remove all files that were not used during the current build, so for example old versions of dependencies. To be able to track this accurately it needs `cargo`/`rustc` to mark the files it uses during the current build, the `-Zmtime-on-use` flag is an unstable flag to tell it to do so.
With this implemented the files uploaded to Travis should only be the relevant ones, keeping the cache minimal and actually usable. This will then mean that future builds will only have to build what has changed and run much faster.
Fixes #243

Sweep the cache before uploading it

---

tide-compression/src/lib.rs
tide-cookies/src/lib.rs
tide-cookies/src/middleware.rs
tide-core/src/app.rs
tide-core/src/endpoint.rs
tide-core/src/lib.rs
tide-core/src/router.rs
tide/src/forms.rs
tide/src/lib.rs
tide/src/middleware/default_headers.rs
tide/src/middleware/logger.rs

Removes the `box_async` macro.
Removes the box async macro, removing indirection from the code.
Tests pass

remove async box macro

---

src/error.rs
tide-core/src/error.rs

A trivial follow-up of PR #216.
Issue: #208

pub use ResultDynErrExt in tide::error

---

examples/graphql.rs
src/querystring.rs
tide-compression/src/lib.rs
tide-cookies/src/middleware.rs
tide-core/src/app.rs
tide-core/src/context.rs
tide-core/src/middleware.rs
tide-core/src/router.rs
tide-headers/src/lib.rs
tide-log/src/lib.rs
tide-slog/src/lib.rs

Rename Context\<Data\> to Context\<State\> according with [RFC #1](https://github.com/rustasync/tide/blob/master/rfcs/001-app-new.md).
Based on #259.
All tests passed.

Rename Context<Data> to Context<State>

---

tests/wildcard.rs
tide-core/src/app.rs

Fixed the documentation for wildcards for path definitions for routing and added a bunch of tests that demonstrate the implemented behavior.
The documentation referred to syntax like :name* but this isn't actually supported by the route recognizer, instead it is looking for *name for named path matches. So I've fixed the explanation and given more examples.
Additionally I added a number of tests for these different path options.
I was starting out with Tide and was trying to get some routes working - in particular capturing the rest of the path and so headed to the documentation to find the suggested wildcard of :path* which should match. Trying to use this caused issues with not being able to find the parameter back (as it turns out it is because the * gets added to the name so you can …

Fix the documentation for wildcards for path definitions to match implementation

---

Cargo.toml
src/error.rs
src/lib.rs
src/middleware.rs
tide-compression/src/lib.rs
tide-cookies/src/lib.rs
tide-core/src/error.rs
tide-core/src/internal.rs
tide-core/src/lib.rs
tide-forms/Cargo.toml
tide-forms/src/lib.rs
tide-headers/src/lib.rs
tide-log/src/lib.rs
tide-querystring/Cargo.toml
tide-querystring/src/lib.rs
tide-slog/Cargo.toml
tide-slog/src/lib.rs

- Extract form.rs into tide-forms
- Extract querystring.rs into tide-querystring
- Refactor `tide` lib.rs
- Move shared internals into `tide_core::internal`
https://github.com/rustasync/tide/pull/252, #162 
All tests passed

Core revamp part 3

---

Cargo.toml
tide-panic/Cargo.toml
tide-panic/LICENSE-APACHE
tide-panic/LICENSE-MIT
tide-panic/src/catch_unwind.rs
tide-panic/src/lib.rs

cc #263, @prasannavl, @yoshuawuyts

Add middleware for catching panics

---

Cargo.toml
examples/templates/tera-hello-world.html
examples/templating_tera.rs

Presently, there are no examples demonstrating rendering HTML; this PR addresses that.
Added an example using [tera](https://tera.netlify.com/) which renders some variables into a template.
Conveys a concise way to render a HTML response with Tide.
Relates to #207, and might even close it? 
Verified functionality locally, and passes tests

Add templating example with tera

---

.travis.yml
tide-cookies/src/middleware.rs

Solves problem mentioned in issue #278. 
Solution according to: https://github.com/rust-lang/rust/issues/61579#issuecomment-500436524
`tide` can not be compiled after nightly 2019-06-01. However, another rustc bug doesn't allow me to compile my project's code for rustc of version lower than 2019-06-15. Therefore I currently have no possible way of compiling my project.
`cargo test`

Workaround for issue #278: works around Rust internal compiler error.

---

Cargo.toml
examples/runtime.rs

Shows how to use a custom http server to run a Tide service, using `http-service-hyper` configured on top of `runtime` as the example.
Fixes #276

Tide on runtime

---

.travis.yml
tide-slog/Cargo.toml
tide-slog/src/lib.rs
tide-slog/src/per_request_logger.rs
tide-slog/src/request_logger.rs
tide-slog/src/set_slog_scope_logger.rs

Replace the existing slog based request logger with more configurable tide-slog integration points.
Better integration with slog using applications and libraries. Previously there was no way to customise what was logged per-request, and no way to get access to the logger from a request. Now those are both provided via `tide_slog::PerRequestLogger`, which `tide_slog::RequestLogger` will use to log the current request; `tide_slog::SetSlogScopeLogger` can also be used to update the `slog_scope` logger automatically within the context of any request.
Doc tests and usage in my own web app.

Rewrite tide-slog to setup a per-request logger instance and support slog-scope

---

.travis.yml
examples/cors.rs
examples/default_headers.rs
examples/hello.rs
examples/hello_envlog.rs
examples/hello_logrs.rs
examples/messages.rs
examples/runtime.rs
src/app.rs
src/lib.rs
tests/wildcard.rs
tide-cors/src/lib.rs

This PR adds async_closure feature gate to the crates that use the feature, in tests and example to make everything compile and work properly again.
This is related to the recent change done in https://github.com/rust-lang/rust/pull/62292

Add async_closure feature gate where needed

---

README.md
examples/cors.rs
examples/default_headers.rs
examples/hello.rs
examples/hello_envlog.rs
examples/hello_logrs.rs
examples/runtime.rs
rfcs/001-app-new.md
src/app.rs
src/lib.rs
tests/wildcard.rs
tide-cors/README.md
tide-cors/src/lib.rs
tide-cors/src/middleware.rs

`async_closure` won't be stable any time soon and are equivalent to closures which return async blocks. 
Related: https://github.com/rust-lang-nursery/futures-rs/pull/1716#issuecomment-508964777

Remove usage of async_closure

---

tide-cookies/src/middleware.rs
tide-core/src/response.rs

Change `()` to return a `204` status code to the client instead of `200`.
```rust
async fn empty(_: tide::Context) -> tide::EndpointResult<()> {
Ok(()))
}
```
Currently the above makes a route that will return `200` with an empty response. 
This is problematic as many libraries expect a `200` to return _something_ in the body and the HTTP RFC strongly recommends to use 204 to indicate "no payload". 
http://svn.tools.ietf.org/svn/wg/httpbis/specs/rfc7231.html#status.200
> Aside from responses to CONNECT, a 200 response always has a payload, though an origin server MAY generate a payload body of zero length. If no payload is desired, an origin server ought to send 204 (No Content) instead. For CONNECT, no payload is allowed because the successful result is a tunnel, which begins immediately …

Set StatusCode for an empty response from `()` to `204`

---

tide-querystring/src/lib.rs

This adds a doc test that shows how to parse the URL query into a `HashMap`.
I found this not very well documented and hope the docs will save some time.

Add doc example showing query parameter extraction

---

.travis.yml
Cargo.toml
tide-compression/Cargo.toml
tide-cookies/Cargo.toml
tide-core/Cargo.toml
tide-cors/Cargo.toml
tide-forms/Cargo.toml
tide-querystring/Cargo.toml

Signed-off-by: Yoshua Wuyts <yoshuawuyts@gmail.com>
Removes the `http-service` patches as a new version has been published.
cargo test passes

remove http-service patches

---

tide-querystring/Cargo.toml
tide-querystring/src/lib.rs

Replaced `serde_urlencoded` with `serde_qs` in `tide-querystring`.
At the time `tide-querystring` was originally authored, `serde_qs` wasn't our first choice because of a concerning bug. Now that concerns have been resolved, replacing `serde_urlencoded` with `serde_qs` may resolve some of Tide's issues.
Existing tests pass.

querystring: replace dependency serde_urlencoded with serde_qs

---

Cargo.toml

Upgrade `mime_guess` to version `2.0.1`.
My hunch is that Dependabot may have ignored this since we explicitly set an `alpha` version of the dependency.  Since `2.0` has now been released, I suggest we update to it.
I'm seeing issues with the `from_path` function used in [`examples/staticfile.rs`](https://github.com/rustasync/tide/blob/master/examples/staticfile.rs#L71) when running tests locally.
All existing tests passed. Examples compiled successfully.

Upgrade mime_guess to version 2.0.1

---

tide-cors/src/middleware.rs

no origin header should be treated as an empty origin header
otherwise, simple HTTP requests like ones made with `curl` will fail with 400 bad request
Pretty much any other framework/server treats the absence of an `origin` header the same as empty `origin` header
Passing no `origin` header should be treated as an empty origin header
otherwise, simple HTTP requests like ones made with `curl` will fail with 400 bad request
Pretty much any other framework/server treats the absence of an `origin` header the same as empty `origin` header
Fixes simple HTTP requests, such as ones made with `curl`
`curl localhost:8000`
`curl -H 'Origin: something.com' localhost:8000`
And to test the cases where it should be rejected, just set the origin to something and then see if any other origin will be …

CORS middleware: better handling of Origin

---

Cargo.toml

There was a patch to fix build on nightly. Since runtime 0.3.0-alpha.7 is out, this patch is not required anymore

updated runtime to 0.3.0-alpha.7, removed patch for crates.io

---

examples/nested_router.rs

Added nested router example. Similar example was here before: https://github.com/rustasync/tide/commit/4bb3d3f19861d567ad319372d4ce93a7c04a7970, but disappeared during refactoring.

Nested router example

---

examples/cookies.rs
tide-cookies/src/data.rs
tide-cookies/src/middleware.rs

`&mut self` doesn't seem to be required, as mentioned in #316.
Change cookie trait function signature on `get_cookie` from `&mut self` to `&self`.
Tide seems to compile fine without requiring a mutable reference. Unsure why the previous behavior may have been required, but I believe there's little need to require mutability when reading cookie values.
Existing tests passed.

cookies: is &mut self required?

---

CHANGELOG.md
Cargo.toml
README.md
examples/default_headers.rs
examples/hello.rs
examples/staticfile.rs
src/app.rs
src/middleware/cookies.rs

This prepares the 0.3.0 release, releasing all the work since the `0.2.0` release up until we started work on splitting the repo into multiple components. This is a snapshot release, and is intended to set us up to rewind the work and improve APIs as outline in #336. Thanks!

Prepare 0.3.0 release

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.toml
README.md
examples/body_types.rs
examples/cookies.rs
examples/messages.rs
examples/multipart-form/main.rs
src/app.rs
src/endpoint.rs
src/forms.rs
src/lib.rs
src/middleware/cookies.rs
src/middleware/default_headers.rs
src/middleware/logger.rs
src/middleware/mod.rs
src/router.rs

Rewinds back the first page of commits per https://github.com/http-rs/tide/issues/336#issuecomment-548556316. Thanks!

Rewind page 3

---

Cargo.toml
README.md
examples/body_types.rs
examples/catch_all.rs
examples/cookies.rs
examples/default_headers.rs
examples/graphql.rs
examples/hello.rs
examples/messages.rs
examples/multipart-form/main.rs
examples/staticfile.rs
src/app.rs
src/context.rs
src/endpoint.rs
src/lib.rs
src/middleware/compression.rs
src/middleware/cookies.rs
src/middleware/cors.rs
src/middleware/default_headers.rs
src/middleware/logger.rs
src/middleware/mod.rs
src/querystring.rs
src/response.rs
src/router.rs
tests/wildcard.rs

Implements page 2 of https://github.com/http-rs/tide/issues/336. Thanks!

Rewind page 2

---

src/lib.rs
src/middleware/mod.rs

`middleware::RequestLogger` made disabled recently, but it can work also in the newest version. I enabled it again. This will resolve #366 .

Enable middleware::RequestLogger again

---

.github/workflows/ci.yaml
Cargo.toml
src/lib.rs
src/request.rs
src/server/mod.rs
src/server/route.rs
tests/nested.rs

~~This is a half-baked version of nesting. Need to strip the path prefix, but I feel this is a good first step!~~ Nevermind, I managed to write necessary mechanics for nesting.
- `HttpService` impl is refactored to use `Endpoint` impl internally.
- Added `Route::strip_prefix`. When used, this will strip the route path prefix from request before passing it to the endpoint.
With this PR, we can finally nest Tide services!
```rust
let mut inner = tide::new();
inner.at("/").get(|_| async { "root" });
inner.at("/foo").get(|_| async { "foo" });
inner.at("/bar").get(|_| async { "bar" });
let mut outer = tide::new();
outer
.at("/nested")
.strip_prefix() // catch /nested and /nested/*
.get(inner.into_http_service()); // the prefix /nested will be stripped here
```
Might need a better name for …

impl Endpoint for Service, for service nesting

---

Cargo.toml
src/endpoint.rs
src/lib.rs
src/request.rs
src/server/mod.rs

This adds more documentation to the APIs. It's by no means complete, but should get us a step in the right direction. Wrote this on the plane, and don't have much time to finish it up in the next week, so figured I'd just put out the PR as-is. Thanks!

Start documenting more

---

src/lib.rs

https://docs.rs/crate/tide/0.5.0 currently isn't building. This fixes that. Thanks!

fix docs build

---

src/response/mod.rs

1. The MIME of `Response::body()` was wrongly documented as `text/plain; charset=utf-8` (copy-and-paste error). It should be `application/octet-stream`.
2. Also documented the MIME types of `Response::body_form()` and `Response::body_json()`.

Fix documentation of Response::body*()'s MIME types.

---

src/router.rs
src/server/route.rs
tests/nested.rs

Follow-up of #364.
`Route::all` catches all HTTP methods. This is mandatory for nesting story, but I missed this somehow.
This PR also adds a convenience method `nest_service`, which turns on nesting flag temporarily and calls `all`.

Add Route::all and Route::nest

---

src/request.rs
tests/querystring.rs

This PR changes the behavior of `.query`: if the caller has not specified any query parameter, we still try to deserialise the desired type from an empty string. 
This allows successful deserialisation of structs which do not have any mandatory field, e.g.
```rust
struct OptionalParams {
author: Option<String>,
theme: Option<String>
}
```
On master, this requires using `unwrap_or` on the outcome of `.query` which I think it's unnecessary.
If you forget about it, it leads to surprising behavior: calling the endpoint with any query parameter (none of which in the struct) would trigger a successful deserialisation, while a call without query params would result in a 400. 
I have also added, for the unhappy case, the deserialisation error in the response body: it makes for a much more …

Change the behaviour of `.query`: optional params and explicit error in the response body

---

src/server/mod.rs

Follow-up to https://github.com/http-rs/tide/pull/347. Disables console printing by default. Thanks!

don't print to console by default

---

examples/json.rs
src/endpoint.rs
src/middleware/mod.rs
src/redirect.rs
src/router.rs
src/server/mod.rs
src/server/route.rs
tests/nested.rs
tests/server.rs

This is a breaking change.
Make `Endpoint::call` generic over lifetime like `Middleware::handle`.

Make Endpoint::call generic over lifetime

---

src/endpoint.rs
src/router.rs
src/server/route.rs
tests/route_middleware.rs

This PR adds per-route middleware support. Current design is as follows:
* `Route::middleware` applies given middleware to the route.
* Following `Route::method` (and `Route::all`) will apply middleware given before.
* Middleware list for the route can be reset using `Route::reset_middleware`.
* When `Route::at` is called, per-route middleware applied to the parent will be applied to the child route by default. This can be reset using `.reset_middleware()`.
Feel free to comment if there is better design!
---
Closes #320.

Per-route middleware

---

src/middleware/cors.rs

The CORS origin header handling fell back to an empty header value. This value is considered valid for `Origin::Any` (wildcard origin). However, if the CORS middleware is restricted to a whitelist of origins, the `is_valid_origin` check correctly fails for an empty origin header
value. Though, since we fell back to an empty value when there is no origin header at all, we fail the validation and consequentially respond with a 403 (forbidden) to such requests.
The [CORS specifications](https://www.w3.org/TR/cors/#resource-processing-model) stats the following for simple cross-origin requests, actual requests and preflight requests:
> If the Origin header is not present terminate this set of steps. The request is outside the scope of this specification.
This PR therefore updates the CORS …

Fix CORS behaviour if there is no origin header

---

src/lib.rs
src/middleware/cors.rs
src/server/mod.rs
src/server/route.rs
tests/cookies.rs
tests/nested.rs
tests/querystring.rs
tests/route_middleware.rs

This implements `HttpService` directly on `Server` removing the need for the intermediate `Service` struct. This allows us to remove `into_http_service` and the `server` submodule making e.g. nesting apps really easy.
```rust
let mut inner_app = tide::new();
inner_app.at("/").get(|_| async { Ok("hello world") });
app.at("/foo").nest(inner_app);
app.listen("localhost:8080").await?;
```
In https://github.com/http-rs/http-types/pull/94 we've introduced the (experimental) Client and Server traits. The hope is that these can replace `http-client` and `http-service` including on Tide directly. Because these traits don't carry a connection this would allow us to bypass `http_service_mock::make_server` and `http_mock_service::TestBackend::simulate` calls entirely by …

Remove intermediate Service struct

---

Cargo.toml
examples/static_file.rs
src/request.rs
src/response/mod.rs
src/server/mod.rs
src/server/route.rs
src/server/serve_dir.rs
tests/nested.rs
tests/route_middleware.rs

Init static file serving support. This depends on https://github.com/http-rs/tide/pull/414.
```rust
#[async_std::main]
async fn main() -> tide::Result<()> {
app.at("/").serve_dir("/public");
app.listen("127.0.0.1:8080").await?;
Ok(())
}
```

Static files

---

src/redirect.rs
src/response/mod.rs

The Redirect endpoint is a special case ("always redirect") of the broader need to conditionally redirect based on some logic within a route handler. This PR moves the creation of a temporary redirect into Response and uses that in the Redirect endpoint. Accidentally, this also eliminates a string clone, since set_header only needs a &str.

Add Response::redirect

---

examples/graphql.rs
src/lib.rs
src/redirect/mod.rs
src/redirect/permanent.rs
src/redirect/temporary.rs
src/response/mod.rs

Follow-up to https://github.com/http-rs/tide/pull/435. Now supports both permanent and temporary redirects, and updated all vocabulary in Tide to be consistent with one another. Thanks!
__edit:__ closes #82
Tide's docs landing now looks really clean:

Add redirect submodule

---

src/lib.rs

Adds logos and favicons to our docs.rs renderings. Because we don't have a custom domain for http-rs I'm hosting it from my own domain for the time being. Thanks!

Adds logos for docs.rs

---

Cargo.toml
examples/sse.rs
src/lib.rs
src/response/mod.rs
src/sse/endpoint.rs
src/sse/mod.rs
src/sse/sender.rs
src/sse/upgrade.rs

This adds initial support for Server-Sent Events. It provides both a pre-made endpoint handler, and an `upgrade` function for use inside manual endpoints. This is the first step towards more elaborate SSE handling. Closes #234. 
As described in my [tide channels post](https://blog.yoshuawuyts.com/tide-channels/) there are many more things we could do around channels. But those rely on having a notion of _identity_ for connecting clients, which in turn relies on session support. Once we have that we can add persistent connection IDs and more!
Additionally we're not sending automated hearbeat messages yet, I believe we're still missing support for these in [http-rs/async-sse](https://github.com/http-rs/async-sse).

Add initial SSE support

---

backup/examples/staticfile.rs
examples/chunked.rs
examples/cookies.rs
examples/graphql.rs
examples/json.rs
src/cookies/middleware.rs
src/lib.rs
src/response/into_response.rs
src/response/mod.rs
src/router.rs
src/server/serve_dir.rs
tests/cookies.rs
tests/querystring.rs
tests/server.rs

Each response requires a StatusCode. Because this is so common throughout Tide we should export this from the top-level. This allows us to simplify the imports in many examples as well. Thanks!

export http_types::{Body, StatusCode}

---

examples/cookies.rs
examples/graphql.rs
src/cookies/middleware.rs
src/endpoint.rs
src/lib.rs
src/log/middleware.rs
src/middleware.rs
src/redirect/temporary.rs
src/response/mod.rs
src/router.rs
src/security/cors.rs
src/server/mod.rs
src/server/route.rs
src/server/serve_dir.rs
tests/cookies.rs
tests/querystring.rs

This means we no long have to define Result<Response> in every single location, which is the way our type alias used to work before #438. Thanks!

Restore default params in tide::Result

---

tests/chunked-encode-large.rs
tests/chunked-encode-small.rs
tests/server.rs
tests/test_utils.rs

Prior to this PR, if a machine has a server running on any of the ports used for testing (808x), tests would fail in unclear ways.  Because socket reuse flags are platform dependent, this PR finds an unused port by temporarily binding to port 0 and using the assigned port.

bind to an unused port in integration tests

---

src/server/serve_dir.rs

We don't want to leak information of which files exist to adversaries, but the origin version of `ServeDir` did.
We are using `canonicalize` to make sure `file_path` is simple, but, unfortunately, it would visit file system, which might be slow, and attackers could count the time that server response, with hundreds of requests, attacker would know which file is exists even it is not sub path of `root`.
read more: https://en.wikipedia.org/wiki/Timing_attack

fix: check directory traversal attack without file system visit

---

Cargo.toml
src/server/serve_dir.rs

this is probably just a stopgap, but resolves the issue wherein browsers download text files served with a generic binary stream content type

🐞 add a minimal version of mime guessing to serve_dir

---

src/cookies/middleware.rs
tests/cookies.rs

🐞 correctly parse multiple values out of the Cookie header

---

README.md

Examples won't work with `0.7.0`.

Fix crate version in README

---

src/response.rs

This is useful for middleware that may want to post-process body data, such as a compression middleware.

Response: add `take_body()` as a way to get the body from a Response

---

src/response.rs

From `http_types::Response`
Useful for e.g. compression middleware where content-length is normally stripped.

Response: expose `remove_header`

---

Cargo.toml
src/middleware.rs
src/request.rs
src/response.rs
src/security/cors.rs
src/server.rs
tests/chunked-encode-large.rs
tests/chunked-encode-small.rs
tests/cookies.rs
tests/nested.rs
tests/querystring.rs
tests/route_middleware.rs
tests/server.rs
tests/test_utils.rs

Depends on #501. Removes all of our use of `http-service`, simplifying our tests significantly. This sets us up to use Surf for our request instantiation in the future as well. Thanks!

Remove http service

---

Cargo.toml

master is currently broken in the following way:
although `cargo test` and `cargo build` work just fine, a project created like
```sh
cargo new tide-example --bin
cd tide-example
cargo add tide --git=https://github.com/http-rs/tide.git
cargo build
```
results in this compile error
```
error[E0277]: the trait bound `std::string::String: log::kv::value::ToValue` is not satisfied
--> /Users/jbr/.cargo/git/checkouts/tide-ea61fd839c4268c0/f575a12/src/server.rs:302:21
|
302 |                     log::error!("async-h1 error", { error: err.to_string() });
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `log::kv::value::ToValue` is not implemented for `std::string::String`
|
= note: required for the cast to the object type `dyn log::kv::value::ToValue`
= …
```

femme is not just a dev dep anymore

---

src/response.rs

This adds `Response::from_res` which enables us to bridge with `Surf` for  authoring proxies conveniently. We couldn't add this as a generic `From` bound because it would conflict with existing implementations.
This was in response to this [this example](https://gist.github.com/jbr/d5c4fec7368eae5a372b6ae403b9c67f) which proxies from surf -> tide, which would allow us to rewrite the core logic from ~10 lines to 2 lines.
```rust
let res = surf::get(...).await?;
Ok(Response::from_res(res))
```

Add Response::from_res

---

src/request.rs
src/response.rs

Part of https://github.com/http-rs/tide/issues/465

Request+Response AsRef and Into impls for inner context access

---

.github/workflows/ci.yaml

the build failure is the purpose of this pr, as master is broken until #511 is merged. this change will catch this sort of (rare) problem in the future

add a no-dev-deps check to ci

---

src/response.rs

Some middleware may want to check headers on the response in order to decide what to do.

Response: expose `header()` from internal response

---

Cargo.toml
examples/hello.rs
examples/static_file.rs
src/log/middleware.rs
src/log/mod.rs
src/server.rs

Relies on https://github.com/lrlna/femme/pull/9. Adds a default logger that supports `log`'s key-value API. A base "hello world" example now looks like this:
```rust
#[async_std::main]
async fn main() -> Result<(), std::io::Error> {
tide::log::start();
app.at("/").get(|_| async move { Ok("Hello, world!") });
app.listen("127.0.0.1:8080").await?;
Ok(())
}
```
---
There's a bit of a design question whether we should expose this as a separate function, or integrate it directly into the framework. I think logging is kind of on the fringe here since it not only captures things going on *inside* the framework; it captures things going on outside of it as well.
I feel that making it a single line to enable logging strikes a good balance between the two -- we make it …

init default logger

---

examples/fib.rs

Small changes for examples/fib.rs.
I think It's slightly more simple.

Fix examples/fib.rs to use Instant::elapsed

---

src/log/middleware.rs

`LogMiddleware` is currently logging the duration for the handler operation using `Duration.as_millis()`.
In case the request gets handled in less than `1ms`, this is what the logger prints:
```
tide::log::middleware --> Response sent
method "GET"
path "/"
status 200
duration "0ms"
```
However, [`std::time::Duration`](https://doc.rust-lang.org/std/time/struct.Duration.html) implements [`Debug` parsing correctly from seconds to nanoseconds](https://doc.rust-lang.org/src/core/time.rs.html#943-955).
With this PR, this is what the logger prints:
```
tide::log::middleware --> Response sent
method "GET"
path "/"
status 200
duration "685.45µs"
```

Use Debug format for std::time::Duration in LogMiddleware

---

src/cookies/middleware.rs
src/endpoint.rs
src/fs/serve_dir.rs
src/lib.rs
src/log/middleware.rs
src/middleware.rs
src/request.rs
src/response.rs
src/route.rs
src/router.rs
src/security/cors.rs
src/server.rs

This satisfies all off `clippy::all` with some fixes from `clippy::pedantic` and `clippy::nursery`.
Note: It's probably easier to review this per commit rather than as the whole diff as it has lots of little changes.

Various Clippy Fixes

---

.github/workflows/ci.yaml
Cargo.toml
benches/router.rs
src/cookies/middleware.rs
src/lib.rs
src/request.rs
src/response.rs
src/route.rs
src/router.rs
src/server.rs
tests/cookies.rs
tests/querystring.rs

- reduce allocations
- add benchmark for `router.route`
- make CookieJar creation lazy
- avoid setting content types twice

Improve performance

---

Cargo.toml
examples/graphql.rs
src/cookies/middleware.rs
src/redirect.rs
src/request.rs
src/response.rs
src/route.rs
src/security/cors.rs
src/server.rs
tests/chunked-encode-large.rs
tests/chunked-encode-small.rs
tests/cookies.rs
tests/nested.rs
tests/querystring.rs
tests/route_middleware.rs
tests/server.rs

A few notes on this mostly-find-and-replace PR:
* This is building against http-rs/async-h1#105 and http-types master, as there are not yet releases for those
* This PR revealed an issue with surf's native client when talking to a server that understands 100-continue. instead of attempting to resolve that, this pr switches to surf's async-h1 client for testing. http-rs/surf#177 represents further work required to address this
* ~~Interacting with a single header value is still a little awkward and this PR is inconsistent about using [0] vs `HeaderValues::last()`~~
* It's surprising that `Response::append_header` panics if the ToHeaderValues cannot be converted but `Response::set_header` does not
* Tests that rely on surf are still a little awkward because of incompatible http-types
* An …

http-types and async-h1 2.0.0

---

src/request.rs
src/server.rs
tests/server.rs

forgot to pr this before 0.9, sorry!

set local and peer addrs in tide

---

src/response.rs

Due to [the way user agents are required to handle the `Set-Cookie` header](https://tools.ietf.org/html/rfc6265#section-5.3), it is not possible to pass a cookie returned by `Request::cookie` to `Response::remove_cookie` if the cookie was originally set with either a domain or a path value.
This PR adds a note about this fact to the `Response::remove_cookie` documentation.

Add warning about domain/path inconsistencies to remove_cookie doc

---

Cargo.toml
src/cookies/middleware.rs
src/fs/serve_dir.rs
src/log/middleware.rs
src/request.rs
src/route.rs
src/server.rs
tests/cookies.rs
tests/nested.rs
tests/querystring.rs
tests/route_middleware.rs

Exposes more methods, removed `Self` from chaining returns, and renamed methods. Also updates to http-types v2.0.1. We should do Response next. Thanks!

Update Request to latest http-types

---

src/lib.rs
src/request.rs
src/response.rs
src/server.rs

The method was renamed in Tide 0.9.
Just 2 cents, it was a bit confusing to me to use "local state" and "global state" as the names because IMHO those terms are normally associated with entire programs. Other frameworks call "local state" as "per request state" or "request scoped state". The "global state" is sometimes referred to as "application scoped state" as well. I'm not familiar with the design and terminology of this framework, but my suggestion would be to clarify/rename those concepts.

Update docs from Request.local to Request.ext

---

Cargo.toml
examples/graphql.rs
src/fs/serve_dir.rs
src/response.rs
tests/chunked-encode-large.rs
tests/chunked-encode-small.rs

Fix the use of the mime crate in the graphql example (brought up by #534), which was a mistake. This pr removes dependence on the mime crate entirely, in preference to http_types::Mime
This pr also allows set_mime to accept an Into<Mime>, and calls through to the http_types::Response::set_content_type

use http_types::mime instead of the mime crate

---

src/request.rs
src/response.rs

Adds `{AsRef,AsMut}<Headers>` impls for `Request` and `Response`. This is useful for generic functions that want to operate on `http_types::Headers`. With this Tide's req/res types can be passed directly to functions that operate on `http-types`'s types:
```rust
fn set_custom(headers: impl AsMut<http_types::Headers>) {
headers.insert("x-custom", "meow");
}
set_custom(&mut req);
set_custom(&mut res);
```

Add AsRef/AsMut<Headers> for Request/Response

---

examples/graphql.rs
src/request.rs
src/response.rs
tests/chunked-encode-large.rs
tests/chunked-encode-small.rs

Brings the methods on both `Request` and `Response` more to parity with each other and to `http_types`.
(Also includes some minor docs clarifications.)

Request, Response: more method parity

---

examples/middleware.rs
src/lib.rs
src/middleware.rs

For discussion, a _functional_ sketch
Due to the lack of AsyncFn types in rust currently, we cannot describe the bounds for an async function that has a lifetime in the arguments. As a result, there's no way to write
```rust
// this example is not possible
app.middleware(|req: Request<()>, next: Next<()>| async move {
next.run(req).await
});
```
and instead function middlewares look like:
```rust
// current signature
fn minimal_middleware<'a>(
request: Request<()>,
next: Next<'a, ()>,
) -> Pin<Box<dyn Future<Output = Result> + Send + 'a>> {
Box::pin(async { next.run(request).await })
}
//--snip--
app.middleware(minimal_middleware);
```
Because the issue is that Next is not owned, it is possible to write simple async signatures for middlewares that exist on either side of the Next call. …

introduce the ideas of Before and After middlewares

---

tests/wildcard.rs

Fix test/wildcard.rs
This PR is related to #509
---
This file used Crate "http_service" and "http_service_mock".
But Cargo.toml does not contain them.
So, I use "Request::new(Method::Get, "http://localhost/*")" and "Server::respond(req)" instead of them.

Fix tests/wildcard

---

Cargo.toml
tests/chunked-encode-large.rs
tests/chunked-encode-small.rs
tests/wildcard.rs

this became necessary because the surf change was not Major but had breaking changes from the previous alpha.
this also explicitly updates surf and async-h1 deps

fix tests on master

---

examples/chunked.rs
examples/cookies.rs
examples/graphql.rs
examples/json.rs
examples/middleware.rs
src/cookies/middleware.rs
src/lib.rs
src/redirect.rs
src/request.rs
src/response.rs
tests/chunked-encode-large.rs
tests/chunked-encode-small.rs
tests/cookies.rs
tests/nested.rs
tests/route_middleware.rs
tests/server.rs

This is a follow-up to #537. Brings Response in line with Request. Thanks!
- Removed `Response::redirect` in favor of `tide::Redirect`
- Renamed `Reponse::set_cookie` to `Response::insert_cookie`.
- Various `Response` methods no longer return `Self`.
- `Response::new` now accepts `u16` as well as `StatusCode` as arguments.
- Added `Response::header_mut`
- Renamed `Response::set_header` to `Response::insert_header`.
- Removed `Response::{body_string, body_form, body_json, body}` in favor of `Response::set_body`.
- Added `Response::swap_body`.
- Renamed `Reponse::set_ext` to `Response::insert_ext`.

Bring response in line with http-types

---

.github/workflows/ci.yaml

this addresses a change in `cookie-0.14.1`'s docs that breaks CI by requiring nightly features

docs --no-deps

---

src/response.rs

This is the last of the chaining methods, presently inconsistent.

Response: borrow for set_status()

---

src/sse/upgrade.rs

Reported in https://twitter.com/fasterthanlime/status/1271398187484491776. Thanks!

fix SSE unwrap

---

src/sse/endpoint.rs
src/sse/upgrade.rs

Follow-up to https://github.com/http-rs/tide/pull/588, covers a case we missed. Thanks!

Fix insert_header unwraps

---

src/sse/endpoint.rs

instead of dropping down to the http-types equivalents. Addresses the issue raised in #571 in a slightly different way

use tide::Response interface in the sse endpoint

---

src/server.rs

This change is an attempt to address #577, and also seems like correct behavior for a server. Regardless of what goes wrong with any individual request, we attempt to continue to respond to subsequent requests. Previously, the use of ? was returning from the `listen` function scope, which shut down the server.
Extracting the inner functions was mostly for clarity and will be further refactored/extracted in future PRs
closes #577

Don't crash the server when there's a listen error

---

src/route.rs
tests/function_middleware.rs

This adds (the missing) support for function middlewares at the route level. #545 already introduced support for function middlewares at the server level.

Allow route based function middlewares

---

src/server.rs

relax the lifetime requirement on server.at(&str)

---

src/security/cors.rs

The CORS middleware currently does some response conversions that are not necessary anymore and that result in loosing cookies for responses to CORS requests. This PR fixes the CORS middleware to retain those cookies by removing the unnecessary conversions.
This PR is similar to https://github.com/http-rs/tide/pull/403, but is adjusted for recent changes to the tide's `Response` and includes a test (@callym I hope you don't mind the additional take on that issue).

Fix CORS middleware to retain cookies

---

src/server.rs

this fixes a critical bug identified in discord, in which multiple simultaneous requests hang indefinitely, introduced in ff00be9414bab3899bb3364bab14390d6e4a641d. Prior to that commit, tide was not awaiting the spawned task, which was the source of this problem.

do not await the spawned task in listen

---

Cargo.toml
tests/wildcard.rs

closes #593 
refs http-rs/route-recognizer#40
This doesn't seem like an ideal solution, but this resolves the conflicting routes issue until there's a route-recognizer release

use route-recognizer 0.2

---

src/response.rs

This was missed in 2baf279 and causes unnecessary warnings.

Response: remove #[must_use] for set_status()

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
.github/stale.yml

On #337, the .github folder was deleted, including important documents such as CONTRIBUTING and CODE_OF_CONDUCT. I opened this PR to restore the files that could be considered relevant. Also, it aims to solve #421 and #491. 
This first commit just restores the documents as they were before #337. Therefore they may need to be updated and some of those files may not be necessary.

restore .github docs

---

examples/chunked.rs
examples/graphql.rs
examples/json.rs
examples/middleware.rs
src/lib.rs
src/response.rs
src/response_builder.rs
tests/chunked-encode-large.rs
tests/chunked-encode-small.rs
tests/server.rs
tests/unix.rs

This PR does several things that are related, but could be distinct PRs. Please let me know if you'd prefer I break them out for independent review.
* changes insert_ext from taking `mut self` to taking `&mut self` to conform to the rest of the response interface
* allows Response::set_status to take any `TryInto<StatusCode>` like `Response::new()` does
```rust
let mut res = Response::new(StatusCode::Ok);
res.set_status(203);
```
* ~~provides a `From<Body> for Response` and uses that conversion in other Body -> Response conversions that already existed.~~ Extracted to #584 
* adds a response builder:
```rust
app.at("/").get(|_| async {
Ok(Response::builder(203)
.body("body")
.header("custom-header", "value"))
})
```

Response builder and related changes

---

Cargo.toml
examples/sse.rs
src/sse/mod.rs
src/sse/sender.rs

in order to allow endpoints to break out of loops
dependent on: http-rs/async-sse#3
closes #591

return a result from sse sender

---

Cargo.toml

3.0.1 was a breaking change, so it has been republished as 4.0.0

update to async-sse 4.0.0

---

Cargo.toml
src/server.rs
tests/log.rs

Print the address in the log string. This adds some redundancy, but this helps bridge this information to non-kv-aware log impls such as the log <-> tracing bridge. Ran into this limitation during a project, and this will help with that. Thanks!

Multi item log

---

examples/error_handling.rs
examples/middleware.rs
src/cookies/middleware.rs
src/endpoint.rs
src/fs/serve_dir.rs
src/log/middleware.rs
src/middleware.rs
src/redirect.rs
src/response.rs
src/route.rs
src/router.rs
src/security/cors.rs
src/server.rs
src/utils.rs
tests/function_middleware.rs
tests/nested.rs
tests/response.rs
tests/route_middleware.rs

Rework middleware so that:
- `next.run().await` always returns a `Response`.
- middleware return of `tide::Result` is always transformed into a `Response` with error set.
Adds the following things to `Response`:
- `pub fn error(&self) -> Option<&Error>`
- `pub fn downcast_error<E>(&self) -> Option<&E>`
- `pub fn take_error(&mut self) -> Option<Error>`
- `impl From<Error> for Response`
- `impl From<crate::Result> for Response`
An example of this being used for an error handling middleware is included at [`examples/error_handling.rs`](https://github.com/http-rs/tide/pull/570/files#diff-e15a65d5009515d8f5b742a83df921f8), and Jacob has transformed someone else's in https://github.com/http-rs/tide/issues/452#issuecomment-640938184.
Dependencies:
- ~~[x] Merge …

Rework middleware to receive Response directly, add optional errors to Response

---

src/fs/serve_dir.rs
tests/serve_dir.rs

Make `ServeDir` return `404 Not Found` response when the requested file does not exist.
`ServeDir`, the internal static file serving endpoint, returns 500 when the file does not exist. But I expected 404.
`ServeDir` did not have any test, so I added some unit tests that call the `call` method directly and some integration tests that request to `ServeDir` using `Route::serve_dir`.
Unfortunately, I could not find any test case to produce a `401 Forbidden` error. The `http_types::Url` type seems to normalize the path segments so I couldn't produce any URL path that refers outside of the desired directory.

Make `ServeDir` return 404 if file does not exists

---

tests/nested.rs
tests/response.rs
tests/route_middleware.rs
tests/test_utils.rs
tests/wildcard.rs

This is a first step in the direction of a [superagent](https://visionmedia.github.io/superagent/)/[supertest](https://github.com/visionmedia/supertest) type testing utility for tide. Currently it just supports simple requests and is not exported for usage outside of tide, but the intent is that as it accumulates more features and stabilizes, it might eventually be public under a tide::testing namespace for tide apps to use.
```rust
// this:
let req = Request::new(
Method::Get,
Url::parse("http://example.com/foo/echo").unwrap(),
);
let mut res: Response = app.respond(req).await.unwrap();
// becomes:
let mut res = app.get("/foo/echo").await;
```
and
```rust
// this:
let req = http::Request::new(
Method::Get,
Url::parse("http://localhost/add_one/3").unwrap(),
);
let mut res: http::Response …
```

introduce an extension trait for testing servers

---

Cargo.toml
examples/middleware.rs
src/cookies/middleware.rs
src/endpoint.rs
src/fs/serve_dir.rs
src/log/middleware.rs
src/middleware.rs
src/redirect.rs
src/route.rs
src/router.rs
src/security/cors.rs
src/server.rs
src/sse/endpoint.rs
src/utils.rs
tests/function_middleware.rs
tests/nested.rs
tests/route_middleware.rs
tests/test_utils.rs

closes #576 
This change does not actually alter the output code, but hides the use of `Pin<Box<dyn Future<Output = T> + Send>>` behind [async_trait](https://docs.rs/async-trait/0.1.36/async_trait/index.html)
In particular, this simplifies implementing Middleware and Endpoint.

use async_trait to simplify async signatures

---

src/security/cors.rs

Browsers are currently unable to read responses the originate from `tide::Error`s when the `CORS` middleware is used. This PR makes sure to add CORS headers to error responses as well.
I guess we want to implement parts of the PR differently (I'll highlight the line I am talking about via a code comment), but I still wanted to open a PR to start the discussion and maybe at least provide a unit test another implementation could reuse.
Refs #525

Add CORS headers to error responses

---

Cargo.toml
examples/graphql.rs
examples/middleware.rs
examples/upload.rs
src/cookies/middleware.rs
src/endpoint.rs
src/fs/serve_dir.rs
src/lib.rs
src/listener/concurrent_listener.rs
src/listener/failover_listener.rs
src/listener/parsed_listener.rs
src/listener/tcp_listener.rs
src/listener/to_listener.rs
src/listener/unix_listener.rs
src/log/middleware.rs
src/middleware.rs
src/redirect.rs
src/request.rs
src/route.rs
src/router.rs
src/security/cors.rs
src/server.rs
src/sse/endpoint.rs
src/sse/upgrade.rs
src/utils.rs
tests/route_middleware.rs
tests/test_utils.rs

Alternative to
https://github.com/http-rs/tide/pull/642
This approach is more flexible but requires the user ensure that their
state implements/derives `Clone`, or is wrapped in an `Arc`.
Co-authored-by: Jacob Rothstein <hi@jbr.me>
Notably while this has less new API surface, this requires more from user code.

Server: require State to be Clone

---

src/response.rs

Allows you to do e.g. `Ok(NotFound)` from an Endpoint / Middleware.
Ergonomics

Response: add From<StatusCode>

---

Cargo.toml
examples/chunked.rs
examples/concurrent_listeners.rs
examples/cookies.rs
examples/error_handling.rs
examples/fib.rs
examples/graphql.rs
examples/json.rs
examples/middleware.rs
examples/nested.rs
examples/redirect.rs
examples/sse.rs
examples/static_file.rs

This is just a general pass of edits for the examples, for consistency and usability.
- Use `#[async_std::main]`
- Use `tide::log::start();`
- Declare more in `use`.
- Improved `error_handling` example.
- GraphQL example now uses `lazy_static!`
Plus more misc minor nits.

Examples: consistency improvements

---

.github/workflows/ci.yaml
examples/error_handling.rs
examples/graphql.rs
tests/chunked-encode-large.rs
tests/chunked-encode-small.rs
tests/log.rs
tests/params.rs
tests/response.rs

This PR enables clippy checks for tests and examples during CI.
Clippy is valuable for tests and examples too, it can spot some mistakes that would make a test wrong.
Having zero Clippy errors after the first clone/fork improves the contributor experience.
`cargo test --all --features unstable`
`cargo clippy --tests --examples`

enable clippy for tests

---

Cargo.toml

Moves `logtest` to dev deps and alphabetizes our dependencies. Thanks!

Reorder deps in cargo.toml

---

Cargo.toml
src/log/mod.rs
src/server.rs

Refs: https://github.com/http-rs/tide/issues/548
The easier to fix that and related issues.
This doesn't tackle `CookiesMiddleware` because it's practically necessary, I think?

src: feature-flag default logger, start/with_level

---

Cargo.toml
examples/sessions.rs
src/lib.rs
src/request.rs
src/sessions/middleware.rs
src/sessions/mod.rs
tests/sessions.rs
tests/test_utils.rs

this is an initial implementation of a session middleware in tide, using a somewhat modified async-sessions crate. this is implemented as a `sessions` feature, which is enabled by default.
this pr reuses some of the signed cookie behavior from the cookie crate without requiring the entire application use signed cookies.  this is to ensure that all users of sessions have signed cookies regardless of the rest of their application settings.
closes: #9 
blocked on: ~~http-rs/async-session#2~~ ~~Publishing async-session 2.0.0 (@yoshuawuyts)~~ @Fishrock123 clarifying change request
related: #541
as part of exploring this approach, I've fully implemented these session stores:
* [sqx+sqlite](https://github.com/jbr/async-sqlx-session)
* [redis](https://github.com/jbr/async-redis-session)
* …

tide sessions

---

src/sse/endpoint.rs
src/sse/upgrade.rs

Relax Sync bound on Fut required on sse::upgrade
`async_std::spawn` doesn't seem to require a `Sync` bound on any `Futures`
used on it. `tide::sse::upgrade` will just `spawn` the `Future` returned by
the `Fn` parameter. With this in mind, the `Sync` bound on that returned
`Future` seems unnecessary.
This, in my experience, seems to conflict with any usages of `async-trait` within that future, since `async-trait` related futures don't appear to be Sync. The main README in the `async-trait` repo seems to suggest the same
> Async fns get transformed into methods that return Pin<Box<dyn Future + Send + 'async_trait>> and delegate to a private async freestanding function.
The code compiles and my project is happy. Not sure how to test this, but I'm open to suggestions!

Relax Sync bound on Fut required on sse::upgrade

---

examples/error_handling.rs
examples/middleware.rs
examples/sessions.rs
src/log/middleware.rs
src/route.rs
src/security/cors.rs
src/server.rs
src/sessions/middleware.rs
src/utils.rs
tests/function_middleware.rs
tests/nested.rs
tests/route_middleware.rs
tests/sessions.rs

Renames `{Route, Server}::middleware` to `{Route, Server}::with`. Closes #665.

Rename .middleware to .with

---

src/log/middleware.rs
tests/log.rs

Currently, nested applications like
```rust
async fn main() -> Result<(), std::io::Error> {
tide::log::start();
app.at("/").nest({
let mut api = tide::new();
api.at("/").get(|_| async { Ok("Hello, world") });
api
});
app.listen("127.0.0.1:8080").await?;
Ok(())
}
```
will log twice. This provides a simple mechanism to ensure that a particular middleware is only run once per request. This approach also supports reentrant routing. This approach also requires no sweeping changes to the tide middleware system to ensure only-once middleware behavior, and also allows the middleware to define the desired behavior if it has already run once for the request.  For example, a more complex logging middleware might record the time spent in each nested application but only …

Only run the log middleware once per request

---

src/request.rs

Implicate Into<tide::Request<State>> for http_types::Request.
Implicate Into<tide::Request<State>> for http_types::Request.
This `State` need trait bound `Default` because this method use `State::default()`
This pull request resolve #465 check box "http_types::Request -> tide::Request (Into)".
Simply, run "cargo test" for exist tests.

impl Into<Request> for http_types::Request

---

README.md

Update README.md to use the new `0.13` version
Updated the `Cargo.toml` example in the README.md to use the new `0.13` version
Make sure people get the newest version when they copy the example lines from the README.md file
Ran the tests and they're all fine, and it's a simple documentation change so did not feel the need to do further testing.

Bump version number in README.md

---

src/server.rs

Currently there's no way to get access to the state on a Server.
I ran into this trying to test an app with a database pool in the State. I had a reference to a Server and wanted to execute statements against the database, but there was no way of doing so.
doctest

expose server state

---

src/request.rs

Fix a broken documentation link that should point to `serde_qs` so that
users do not have to search themselves.
Simply fix a broken documentation link referring to the external `serde_qs` crate so that users can click it on `docs.rs` instead of searching for the crate themselves.
This allows the documentation to be followed slightly more easily and means `cargo doc` produces no warnings (other than those created by [this issue](https://github.com/rust-lang/cargo/issues/6313)).
This affects no tests and makes no changes to the functionality, so the unit tests pass before and after the change.

Fix a broken documentation link

---

src/log/middleware.rs

This should help demystify some cases when client errors are determined by parsing and propagated via `?`.
Makes the logger display an associated error message when this warning occurs, if possible.
Also clarified that a client error occured.
For never users some cases of client errors being caused by e.g. body parsing and then propgated via `?` may be unobvious. This helps demystify that.
Manual curl to the json example. Output:
```
tide::log::middleware Client error --> Response sent
message missing field `name` at line 1 column 2
method POST
path /submit
status 422
duration 73.9µs
```

log: display client error messages when possible as warnings

---

src/route.rs

I found this method in route.rs:
```rust
pub fn nest<InnerState>(&mut self, service: crate::Server<InnerState>) -> &mut Self
where
State: Clone + Send + Sync + 'static,
InnerState: Clone + Send + Sync + 'static,
{
self.prefix = true;
self.all(service);
self.prefix = false;
self
}
```
I'm not sure if this is expected behavior but I assume that if self.prefix was set to true before calling `nest` it should stay true.
This is a trivial code change, all tests still pass, however I could try to add a regression test for this. Let me know if this is required
This does introduce a small change in behavior but it only impacts code that uses the unstable `strip-prefix` method

Bugfix, route prefix was always set to false after calling nest

---

src/endpoint.rs

Right now adding endpoints dynamically is difficult because only types that implement the Endpoint trait directly can be added. When you don't know in advance which endpoint you want to add in a certain situation it can be useful to be able to add boxed endpoints. This implementation makes this possible.
I did not add any tests for this. It seems like a trivial piece of code where the test will probably be more fragile than the code itself.

implement Endpoint trait for Box<dyn Endpoint>

---

Cargo.toml
src/log/mod.rs

Make the `femme` dependency optional, enabled via the `logger` feature.
Allows you to use a different log crate and `femme` doesn't have to be installed.
Technically speaking this is a breaking change in the case where someone removed the `logger` feature and still used `tide::log::LevelFilter`.

Make `femme` dependency optional

---

src/endpoint.rs
tests/endpoint.rs

This pr fixes the Endpoint implementation for boxed endpoints. And adds a test for this fix.
In the previous implementation the call method for the boxed endpoint just called itself and not the call method of the endpoint inside the box. This caused an infinite loop.

Fix missing as_ref that caused boxed endpoints to enter an infinite loop

---

Cargo.toml
README.md
src/lib.rs

The current docs are a bit much. This is an attempt to be more to the point. More showing, less telling. Thanks!
__edit:__ all the how-to's should move to their own guides. Planning to do that over the course of next week.

rework landing docs

---

.github/workflows/ci.yaml
src/route.rs
src/server.rs

The rc_buffer thing is similar to https://github.com/http-rs/surf/pull/242, refs https://github.com/rust-lang/rust-clippy/pull/6044

ci, src: run clippy on nightly, apply fixes

---

Cargo.toml
src/server.rs
tests/log.rs
tests/nested.rs
tests/response.rs
tests/route_middleware.rs
tests/server.rs
tests/sessions.rs
tests/test_utils.rs
tests/wildcard.rs

In order to facilitate testing, it is convenient for tide::Server to implement http_client::HttpClient.  This allows surf to be used for testing, with only the following shim:
```rust
#[cfg(test)]
mod tests {
use super::*;
pub fn test_client<State>(server: Server<State>) -> Client
where
State: Debug + Unpin + Sync + Send + Clone + 'static,
{
let mut client = Client::with_http_client(Arc::new(server));
client.set_base_url(Url::parse("http://example.com/").unwrap());
client
}
#[async_std::test]
async fn test() -> tide::Result<()> {
let app = build_app().await;
let body = test_client(app).get("/").recv_string().await?;
Ok(())
}
}
```
If http-rs/surf#229 is merged, this would allow:
```rust
let app = tide::new();
use surf::ClientExt;
app.get("http://example.com/").recv_string()?;
```
this is …

add a http_client::HttpClient implementation for tide::Server

---

Cargo.toml
examples/fib.rs
examples/upload.rs
src/lib.rs
src/request.rs
tests/params.rs
tests/wildcard.rs

This PR removes the `parse` portion of `Request::param`, making that an explicit step that needs to be called by end-users. This was inspired by my analysis in https://github.com/rust-lang/rust/pull/75435#issuecomment-695805123 on similar ergonomics issues for a stdlib API. As a result many of our tests that want to extract a `&str` or `String` from the params are more intuitive.

Remove parsing from `Request::param`

---

examples/error_handling.rs
src/log/middleware.rs

Also adds the error type name.
Fixes: https://github.com/http-rs/tide/issues/703

Logger: properly print debug from errors

---

README.md

The readme example listens on port 8080 but the curl examples following it were hitting 8000.

Fix port in README

---

src/sessions/middleware.rs
tests/sessions.rs

We are using tide as a session/authentication context and we need to set the domain of the cookie as the root domain on the SessionMiddleware.
This PR adds the hability to set de cookie domain through the SessionMiddleware builder.

Add with_cookie_domain method to SessionMiddleware

---

src/request.rs

param doesn't infer its return type, it always returns a string.
Document it accordingly.

Fix param documentation

---

src/listener/concurrent_listener.rs
src/listener/failover_listener.rs
src/listener/mod.rs
src/listener/parsed_listener.rs
src/listener/tcp_listener.rs
src/listener/to_listener_impls.rs
src/listener/unix_listener.rs
src/prelude.rs
src/server.rs
tests/log.rs

Alternative to #724's `Server::listen_with` implementation, as suggested by @jbr.
This patch introduces a mechanism to "start listening" but don't "start accepting requests" quite yet. This enables logging in between the two actions, which fixes #712  An example:
```rust
use tide::prelude::*;
app.at("/").get(|_| async { Ok("Hello, world!") });
let mut listener = app.bind("127.0.0.1:8080").await?;
for info in listener.info().iter() {
println!("Server listening on {}", info);
}
listener.accept().await?;
```
In order for this to work we had to also adjust `Listener::listen`, breaking it up into `Listener::bind` which opens the connection, and `Listener::accept` which starts accepting the connections. Terminology-wise "listening" is the action of "binding" + …

Add `Server::bind`

---

examples/state.rs

I found this example useful in understanding how a tide-based server can
handle and maintain state.

Add simple state example

---

src/fs/serve_dir.rs

Currently, `serve_dir` is using `str::trim_start_matches`, which may strip the prefix multiple times.
I've changed this to use `strip_prefix`, which will only strip it once.
I think this unwrap is okay, because the prefix is guaranteed to be there. Do tell me if I'm wrong.

In `serve_dir`, only strip the prefix from the start of the path once.

---

src/listener/to_listener_impls.rs

- Implements `ToListener` for  `&String`.
- Implements `ToListener` for `(String, u16)` and `(&String, u16)`.
Resolves #744

Add more `ToListener` implementations

---

src/lib.rs

Inlining these docs causes them to be perpetually out-of-date, since Docs.rs only builds on the actual containing crate publish.

docs: do not inline docs from deps that drift

---

examples/static_file.html
examples/static_file.rs
src/fs/mod.rs
src/fs/serve_dir.rs
src/fs/serve_file.rs
src/route.rs

This pr adds a serve_file method alongside the already existing `serve_dir` method.

Add `serve_file` method to route

---

Cargo.toml

This updates us to a secure version of async-h1 as the minimal supported version. For anyone running Tide in production either a fresh install or `cargo update` will get you the latest version async-h1 as well because it's semver-compatible with older versions. However this makes sure that if you update to a recent tide, you will never have an old version of async-h1.

Update async-h1 to v2.3.0

---

src/lib.rs

The example server binds port `8080`:
https://github.com/http-rs/tide/blob/46bf28a13be9951e7a61f647f98d5232106d61fb/src/lib.rs#L36
...but the example `curl` invocations post to port `8000`:
https://github.com/http-rs/tide/blob/46bf28a13be9951e7a61f647f98d5232106d61fb/src/lib.rs#L47-L51
This patch modifies the `curl` invocations to post to port `8080`, instead.

Fix port in `curl` invocation in example.

---

.github/workflows/ci.yaml

The build was failing for a while because clippy, doc-tests and cargo fmt are run on rust nightly. Unfortunately the nightly build does not always include all these components. In this case cargo fmt was failing.
It used to be necessary to run clippy on nightly so I assume this is why these steps were run on nightly for the Tide build. This is not necessary anymore. This pr changes the build script to run these steps on rust stable.

ci: run clippy, docs and fmt checks on stable

---

README.md

The example code doesn't build with the old versions anymore.

Update version numbers of deps for README example

---

src/endpoint.rs
src/route.rs

I refactored away some duplicate code in how middleware is added to endpoints. There is still some duplicate code left between the `Route::method` and `'Route::all` but factoring this out will probably require some lambda magic and will not improve readablilty.
A check to see if there was middleware present was done in the same way in several places. This small refactoring moves
that check into the code that adds middleware onto an endpoint. This reduces code duplication and improves readability
Middleware has decent test coverage. The tests that touch this piece of code still succeed. This code does not add any functionality so no additional tests should be neccesary.

Refactor duplicate code

---

src/lib.rs

Hello :)
First of all, thank you for creating and maintaining this crate. I enjoy it :)
This PR fixes the documentation for the "Getting started" example inside `lib.rs`. Without `serde` in dependencies, the compiler throws the following error:
```
error[E0463]: can't find crate for `serde`
--> src/main.rs:5:17
|
5 | #[derive(Debug, Deserialize)]
|                 ^^^^^^^^^^^ can't find crate
|
= note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
error: aborting due to previous error
```
I noted that the similar example in README has `serde` in place and copied it here :)

docs: Add missing `serde` requirement in example

---

Cargo.toml

Upgrade to http-types 2.10 with optional support for cookies, and make
use of that support to reduce dependencies.

Reduce dependencies when cookies not enabled

---

Cargo.toml

Part of https://github.com/rust-lang/log/issues/437
The `log` crate has an unstable structured logging API under the `kv_unstable` feature. In previous releases, if you specified both the `kv_unstable` and `std` features of `log` like so:
```toml
log = { features = ["std", "kv_unstable"]}
```
you'd get support for standard library types in `log`'s structured logging API.
Going forward, this functionality is now gated under `kv_unstable_std`:
```toml
log = { features = ["kv_unstable_std"]}
```
This change was made because we need to enable features in optional dependencies when both the `std` and `kv_unstable` features are enabled, which isn't currently supported by Cargo.
This PR updates this library to follow the new approach. It can be merged at any time and is currently non-blocking, …

Update log to use kv_unstable_std instead of std

---

README.md
examples/upload.rs

Hi, @jbr, I have deleted async-graphql.rs from tide/examples repository, and only added repo links to the example applications list section.
- typo locahost -> localhost in examples/upload.rs.
- Add example tide-graphql-mongodb: Clean boilerplate for graphql services using tide, rhai, async-graphql, surf, graphql-client, handlebars-rust, jsonwebtoken, and mongodb.
- Graphql Services: User register, Salt and hash a password with PBKDF2 , Sign in， JSON web token authentication, Change password， Profile Update, User's query & mutation, and Project's query & mutation.
- Web Application: Client request, bring & parse GraphQL data, Render data to template engine(handlebars-rust)， Define custom helper with Rhai scripting language.
- Add example surfer: the complete blog example, built on pure …

Add 2 examples, and typo locahost -> localhost in examples/upload.rs 

---

src/sessions/middleware.rs
tests/sessions.rs

Closes #801 
Browsers treat SameSite policy as Lax if it is not specified and this behaviour is more intuitive.

Set SameSite policy Lax as default

---

examples/static_file.rs
src/fs/serve_dir.rs
src/route.rs
tests/serve_dir.rs

Fixes: #777 
I had fixed that `serve_dir` precede to other existing routes. 
It has a little breaking changes that specified routing path of `serve_dir` to add suffix wild card asterisk. 
But unit/integrate test has certainly all passed and it has changed examples as anyone can make sense.

bugfix : serve_dir doesn't precede to other route

---

src/server.rs

Updates the docs in server.rs to reflect the renaming of Server::middleware to Server::with.

Update server.rs docs to reflect method rename

---

Cargo.toml
src/lib.rs
src/listener/unix_listener.rs
src/sessions/middleware.rs

this is a patch level change for tide, as it introduces no changes to the public api
also fixes several unrelated clippies. chose to allow clippy::len_without_is_empty because that's part of the public api and any changes to that should be done in a more considered fashion than "trying to fix a clippy lint"

update async-session to 3.0.0

---

src/response.rs

In case Tide is built without support for cookies (specifically `http-types/cookies`), some of the exports used in `Response` are not available. I guess the issue didn't pop up earlier because some other dependencies did enable `http-types/cookies` on their own.

Fix response if cookies are not enabled

---

src/route.rs

I was surprised by this behavior, so I thought it useful to add it to the documentation

Document behaviour of nested overlapping routes

---

src/route.rs

As someone new to the library, I worry about the security builtin routes, and here I had to check the (well documented) source to find what i was looking for. This PR adds the information to the route documentation itself.

Document security of serve_dir router

---

examples/static_file.rs

There was some confusion how the `serve_file` example worked (https://github.com/http-rs/tide/issues/796)
This comment in the example might prevent this in the future

add a comment to the serve_file example to fix confusion mentioned in issue #796

---

Cargo.toml
src/request.rs
src/route.rs
src/router.rs
tests/wildcard.rs

[routefinder](https://github.com/jbr/routefinder) represents a complete rewrite of the route-recognizer behavior
Breaking changes:
* there can only be one wildcard per route
* unnamed params are not supported
* the prioritization between routes may not be identical in some cases, but there are no known examples of this
There may be an incidental performance improvement of several microseconds per request
closes #783 
a step towards #797

try using routefinder

---

Cargo.toml
src/route.rs

See [routefinder@v0.5.0](https://github.com/jbr/routefinder/releases/tag/v0.5.0) release notes. No apis that tide uses directly were changed. There may be a slight performance improvement in this release, but not to a degree that really matters. This is not particularly important for tide, but we might as well keep on latest versions.

upgrade routefinder to 0.5.0

---

README.md

This confused me initially, as I thought https://github.com/http-rs/surf was meant with the title. On another note, as surf is also related, maybe it should be linked too?

docs(readme): correct surfer link

---

examples/catflap.rs
examples/chunked.rs
examples/concurrent_listeners.rs
examples/cookies.rs
examples/error_handling.rs
examples/hello.rs
examples/json.rs
examples/nested.rs
examples/redirect.rs
examples/sessions.rs
examples/sse.rs
examples/state.rs
examples/static_file.rs
examples/upload.rs
src/lib.rs
src/server.rs
tests/log.rs

Not a large code change, but probably still worth discussing. Here's a PR for that discussion

remove the logger from the default middleware

---

Cargo.toml
src/lib.rs

Since we're in the 0.17 beta, we can safely make this feature non-default.

Upgrade async-sse to 5.1.0 and make it optional

---

Cargo.toml
src/log/middleware.rs

Since we're in the 0.17 beta, we can make breaking API changes, such as
making previously default features non-default.
Leave `h1-server` on by default, since tide isn't an HTTP server without
it. Disable all other optional features by default, and let the user opt
into them as needed.

Make several features non-default

---

Cargo.toml
src/security/cors.rs

Hi team, thanks for all the work you guys are doing towards tide.
This PR is for issue https://github.com/http-rs/tide/issues/863.
Our use case is that vercel dynamically generates domains for previewing the changes and our test environment is using tide.
There were a couple of decisions that I am happy to rectify if you see any issues.
1.) That it was okay to bring another dependency, in this case latest [regex](https://github.com/http-rs/tide/compare/main...marcoslopes:main#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R51)
2.) Implementing PartialEq and Hash manually is ok, and decided to allow the most permissive implementation, by that I mean, the contents of the Origin variants is what is actually checked, and not only the variants themselves.
Thank you very …

Allow cors origin to be dynamically matched

---

README.md

I've submitted a simple tide-jwt middleware for supporting jwt authorization bearer tokens. This supports validating, encoding and decoding claims as passed into the utility functions and when configuring the middleware.

Add tide-jwt middleware implementation to readme

---

Cargo.toml
examples/catflap.rs
examples/chunked.rs
examples/concurrent_listeners.rs
examples/cookies.rs
examples/error_handling.rs
examples/hello.rs
examples/json.rs
examples/middleware.rs
examples/nested.rs
examples/redirect.rs
examples/sessions.rs
examples/state.rs
examples/static_file.rs
examples/upload.rs
src/fs/serve_dir.rs
src/fs/serve_file.rs
src/lib.rs
src/listener/concurrent_listener.rs
src/listener/failover_listener.rs
src/listener/tcp_listener.rs
src/listener/unix_listener.rs
src/log/middleware.rs
src/log/mod.rs
src/route.rs
src/server.rs
src/sessions/middleware.rs

Continue using logging internally, but don't re-export log macros or
mechanisms to start logging.

Stop re-exporting logging details from tide::log

---

src/listener/concurrent_listener.rs
src/sessions/middleware.rs
tests/sessions.rs

Addresses #811 and allows the session middleware to be configured to override the secure cookie attribute

Session cookie secure attribute

---

.github/workflows/ci.yaml

Currently tests are not passing due to the logger feature not being included in CI. This should fix that

Fix github ci to include logger with tests

---

src/security/cors.rs

The symmetrical test here fails a nonminimal bool test, but it looks fine to skip in this case

Fix github ci clippy tests on nonminimal bool test

---

examples/sse.rs
src/sse/endpoint.rs
src/sse/upgrade.rs

Fixed below two things in sse.
1. Use the git version of tide, I had below error. Fixed it refere #889.
```rust
error[E0433]: failed to resolve: could not find `error` in `log`
--> tide/src/sse/endpoint.rs:51:22
|
51 |                 log::error!("SSE handler error: {:?}", err);
|                      ^^^^^ could not find `error` in `log`
error[E0433]: failed to resolve: could not find `error` in `log`
--> tide/src/sse/upgrade.rs:22:18
|
22 |             log::error!("SSE handler error: {:?}", err);
|                  ^^^^^ could not find `error` in `log`
For more information about this error, try `rustc --explain E0433`.
error: could not compile `tide` due to 2 previous errors
```
2. example/sse.rs had build error.
```rust
error[E0425]: cannot find function `start` in module `tide::log` …
```

Fix sse log change to femme and kv_log_macro

---

src/endpoint.rs

Remove obsolete part of documentation which refers to attributes which were removed in [commit 6eeb9b33](https://github.com/http-rs/tide/commit/6eeb9b33e0d9ff63ccaca0c161d6389bb6b14f86#diff-b7dd6c6dc06c9c5da00a0c048df395e5fed282392d70a222b1d0e34706d9baf3) (which already removed a line from this paragraph)

Remove obsolete mention of Nightly in the Endpoint examples

---

src/listener/mod.rs

The `Listener` trait depends on `Sync` and `Send`, but tide only actually makes
use of `Send`. Remove the `Sync` requirement, which makes it easier to
implement `Listener`.

Don't make Listener require Sync
