http-rs/tide

- examples/named_path.rs
- src/head.rs
Added an extractor type based on the sketch in #13 as well as an example of implementing the traits to make it work
> Named path extractors

- .travis.yml
- Cargo.toml
- src/app.rs
> Revert "Allow running Tide on non-Tokio executors"

- src/endpoint.rs
Merged `end_point_impl_with_head!` and `end_point_impl_no_head!` into one macro.
> Refactor `end_point_impl!`

- src/head.rs
> Extracting the query portion of the URL

- src/app.rs
- src/endpoint.rs
- src/middleware/default_headers.rs
- src/middleware/mod.rs
- src/router.rs
Experimental implementation of #54.
* Do we need to keep request-response middleware trait?
> Experiment: Wrap-around middleware

- README.md
> Fix the travis badge again

- src/response.rs
> Set default content type for strings to utf-8

- examples/body_types.rs
- examples/computed_values.rs
- examples/default_headers.rs
- examples/graphql.rs
- examples/hello.rs
- examples/messages.rs
- examples/multipart-form/main.rs
- examples/named_path.rs
- examples/simple_nested_router.rs
- src/body.rs
Solves #78. Updated all of the examples to use the same port, also added the address line to the output.
> Use the same port in examples

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
Adds github templates for filing bugs, feature requests and PRs
> add github templates

- examples/body_types.rs
- src/app.rs
- src/body.rs
- src/endpoint.rs
- src/head.rs
- src/lib.rs
- src/response.rs
Add code examples to API docs.
Added some examples to most of the core components (app, endpoint, body, head).
See #17 
Tested with `cargo test --doc`
> Add examples to API docs

- src/middleware/mod.rs
This PR reduces the number of allocations by creating `FutureObj` in `RequestContext::next` only when necessary.
Building `FutureObj` for every middleware is unnecessary, and it'd have allocation overhead because of `Box::new`. So I've cleaned this up.
No functionality changes are expected (and it's pretty obvious), so I didn't write or run any new tests. All existing tests passed. Running some benchmark would be nice though.
- Well, this is more like an improvement.
> Make RequestContext::next allocate less

- Cargo.toml
This fixes CI as outlined in https://github.com/rust-net-web/tide/issues/130.
A patch has been submitted to our broken dependency, but this allows us to keep building in the meantime.
CI should pass again. Builds locally.
> temporarily override fix-cookie source

- Cargo.toml
- examples/cli_parsing.rs
Simple example to show external configuration integration with a Tide application
Manual tests.
> Add example to show CLI parsing integration with tide app

- Cargo.toml
Fixes GH-130
builds & tests pass.
> Fixes GH-130

- .travis.yml
Signed-off-by: Yoshua Wuyts <yoshuawuyts@gmail.com>
Pin rust nightly version on CI.
Fixes #134 
Tested version locally and tests pass
> pin nightly version on CI

- .github/PULL_REQUEST_TEMPLATE.md
- Cargo.toml
Changed references from old repository to the current one. There are also references to `rust-net-web` in [CHANGELOG.md](changelog.md), which I can update if it should go as part of this PR.
> Update references to old repository

- src/lib.rs
Inlines the doc declarations.
cargo doc
> inline docs

- README.md
Redo the readme to make it more friendly. [rendered](https://github.com/rustasync/tide/blob/examples/README.md)
We were missing examples, and more details on how we operate. This makes the README a bit more compelling, which should also help when linking to Crates.io.
Just a readme, copied the example from the examples dir.
> redo readme

- README.md
The example code on README.md got an error due to `?`.
Tested on `rustc 1.36.0-nightly (8aaae4294 2019-04-19)`
> fix: error on example code

- src/lib.rs
Compiler pragma updates
- Drop the `forbid` to `deny` for `rust_2018_idioms`
- Add `future_incompatible` lint
- Fix typos in comment below
https://github.com/rustasync/tide/pull/175
Compilation successful!
> pragma updates

- src/cookies.rs
This fixes some minor nits identified by @aturon during review of PR https://github.com/rustasync/tide/pull/170
Remove unnecessary clone
All existing tests passing.
> Fix minor bugs found during review

- Cargo.toml
Add keywords and categories information
Easier to find in crates.io
> Add info to Cargo.toml

- src/app.rs
- src/route.rs
Currently method link is plain text, Because link format is invalid. I fixed it.
I see new documentation.
> Fix doc links

- Cargo.toml
- src/app.rs
> Fix build fail on master

- src/app.rs
This PR fixes ignored doc-test for `App`.
The code fence was not closed, so I closed it.
Also, since the code has not been tested recently, some changes were necessary. I used the simplified version of `examples/messages.rs` for this.
`cargo test` run passes.
> Fix ignored App doc-test

- Cargo.toml
- examples/staticfile.rs
This adds an example for a simple static server.
My [personal server](https://github.com/wafflespeanut/waffles.space/tree/master/server) had been using [iron](https://github.com/iron/iron/) for over a year - I finally found time to switch to something else and my choice was tide :smile: - I wrote a simple static server using tide and I thought I could strip down some code and add it as an example in this repository.
[My website is alive and well](https://waffles.space). I haven't added any unit tests here. I thought it's an overkill for an example.
> Add example for serving static files

- Cargo.toml
- examples/multipart-form/main.rs
- Update serde dep versions
- Update multipart to latest
- Fix broken multipart example
- Resolves https://github.com/rustasync/tide/pull/213
All tests pass
> update deps, fix multipart example

- README.md
- tide/src/lib.rs
Avoid letting the example bitrot
In tests
> Check example in readme compiles during testing

- tide-compression/README.md
Improve curl command consistency, position of `-v` and quoting of url.
Improve curl command readability by readers.
> Improve curl command consistency

- examples/body_types.rs
Add type declaration, because it becomes unit type by type indefinite
Ci failed
run clippy and test
> fix clippy warnings

- tide-core/src/app.rs
> Propagate hyper error on serve failure

- Cargo.toml
- src/lib.rs
- tide-compression/README.md
- tide-cookies/src/lib.rs
- tide-core/src/lib.rs
- tide-cors/README.md
- tide-cors/src/lib.rs
- tide-panic/src/lib.rs
> Adjust docs for consistency

- Cargo.toml
- tide-compression/Cargo.toml
- tide-cookies/Cargo.toml
- tide-core/Cargo.toml
- tide-forms/Cargo.toml
- tide-headers/Cargo.toml
- tide-log/Cargo.toml
- tide-querystring/Cargo.toml
- tide-slog/Cargo.toml
Avoids forcing features users don't use on by accident.
> Disable default-features everywhere

- Cargo.toml
- src/app.rs
- src/router/core.rs
- tide-compression/Cargo.toml
- tide-compression/src/lib.rs
- tide-cookies/Cargo.toml
- tide-cookies/src/middleware.rs
- tide-core/Cargo.toml
- tide-core/src/endpoint.rs
- tide-cors/Cargo.toml
- tide-cors/src/middleware.rs
- tide-forms/Cargo.toml
- tide-forms/src/lib.rs
- tide-headers/Cargo.toml
- tide-headers/src/lib.rs
- tide-log/Cargo.toml
- tide-log/src/lib.rs
- tide-panic/Cargo.toml
- tide-querystring/Cargo.toml
- tide-slog/Cargo.toml
- tide-slog/src/lib.rs
> Update for futures alpha.17

- src/lib.rs
- tide-cors/examples/cors.rs
- tide-cors/src/lib.rs
- tide-cors/src/middleware.rs
Cors middleware extension. Added validation of origin header.
https://github.com/rustasync/tide/pull/262#pullrequestreview-242949154
By test code, also by example.
> Cors middleware extension

- examples/staticfile.rs
> Fix clippy error in static file example

- .travis.yml
- Cargo.toml
- src/lib.rs
- tide-core/Cargo.toml
- tide-core/src/lib.rs
Closes #300 
Closes #302 
Removed this feature flag because it was not even used
> removed existential_type feature

- tide-slog/Cargo.toml
> Fix tide-slog docs.rs metadata

- tide-slog/Cargo.toml
> Update slog-stdlog to 4.0

- tide-core/Cargo.toml
- tide-core/src/response.rs
Related to #321.
If JSON Serialize failure return 500 and Error message.
> feat(core): If JSON Serialize failure return 500 and Error message

- README.md
Quick drive-by PR to remove the feature flag from the README now that async is stable :rocket:
> Remove feature flag from README.md

- .github/workflows/ci.yaml
- Cargo.toml
Blocked on http-rs/http-service#49. Luckily all tests pass.
> Update to futures 0.3

- src/request.rs
- tests/server.rs
Tiny fixes to the api-cleanup branch
> Remove unneeded imports and don't use select

- Cargo.toml
- examples/json.rs
> Json example

- README.md
Adds https://blog.yoshuawuyts.com/tide/ to the reading list. Thanks!
> add latest tide blog post

- CHANGELOG.md
> Fix the path on CHANGELOG

- src/middleware/cookies.rs
- src/request.rs
- tests/cookies.rs
Implements https://github.com/http-rs/tide/issues/412, thanks!
> Remove Result from Request::cookie

- examples/fib.rs
This example allows you to learn a bit of route parsing and how to bind URL parameters to variables.
This example, combined with the hello and json ones will hopefully give a newcomer enough data to start building simple yet powerful webservers.
> Fibonacci sequence example.

- examples/chunked.rs
Adds a chunked example. This is useful for checking our chunked encoder. Thanks!
cc/ @dignifiedquire
> add chunked example

- tests/chunked-encode-large.rs
- tests/chunked-encode-small.rs
The large test seems to be failing. Sibling PR to https://github.com/http-rs/async-h1/pull/90. Thanks!
> Add chunked encoding tests

- README.md
- src/lib.rs
Mentions `async-std` and its `features = ["attributes"]` clearly.
Fixes https://github.com/http-rs/tide/issues/431
Let me know if there are any wording changes or something else you'd want to improve in this PR!
> Documentation: Add "Getting Started" section to Readme and lib.rs.

- src/lib.rs
Polishes the initial docs somewhat. Thanks!
> Doc fixes for lib.rs

- README.md
also updates the hello world example in the markdown to return a Result
> Include instructions on running examples in README

- examples/nested.rs
Didn't see any examples for nesting tide servers so I created a simple example
> Add an example for nesting a tide server

- README.md
adds the tide channels post to the resources. Thanks!
> Add Tide channels post to README

- README.md
and provide instructions for using nginx as a reverse proxy
> 📖 add a mention of the http/1.1 protocol limitation

- Cargo.toml
@tirr-c has done key work around designing and implementing both middleware and routing, and I think they deserve to be acknowledged for that.
> add @tirr-c as co-author to Cargo.toml

- src/request.rs
- src/response.rs
> Impl Index for Request,Response

- tests/unix.rs
Noticed https://github.com/http-rs/tide/pull/539 was failing, which seems caused by #531 not having been updated for master. This patch fixes that. Thanks!
> Fix unix tests

- Cargo.toml
- src/sse/sender.rs
Updates `async-sse` to v3.0.0. Thanks!
> update to async-sse v3.0.0

- src/response.rs
and use that in other Froms
Cherry-picked out of #580, which contains the example and documentation updates for this change
> provide a From<Body> for Response

- tests/unix.rs
not sure how this compiled and passed ci without this
> fix tempfile usage

- Cargo.toml
> update http-types to 2.2.1

- examples/upload.rs
closes #617 
cc: @LukeMauldin, let me know if this is something like you had in mind
> add an upload example

- src/middleware.rs
- src/request.rs
- src/response.rs
fixes some doc comment and removes some old commented out code
> Comment cleanup fixes

- src/request.rs
> add a doc example for Request::body_form

- src/request.rs
does what it says on the label ☝️
> add a doc example for Request::query

- src/lib.rs
- src/request.rs
- tests/params.rs
> Don't panic on missing path param

- README.md
I just bumped the version number.
> Bumped version number.

- README.md
Refs: https://github.com/http-rs/tide/pull/651
Refs: https://github.com/http-rs/tide/issues/656
> docs: add logging start to readme example.

- tests/server.rs
Updates to the latest surf alpha. Unblocks https://github.com/http-rs/tide/pull/704 https://github.com/http-rs/tide/pull/705. Thanks!
> Update to latest Surf alpha in tests

- Cargo.toml
- src/lib.rs
- src/request.rs
- src/security/cors.rs
- src/server.rs
This seems related to #548. It was mostly done as an experiment to get my feet wet in the codebase, but I figured it could be useful for other people as well.
> Add an optional cookies feature

- src/route.rs
The code now matches the description.
Resolves #659
> Fix `Route::serve_dir` docs

- README.md
https://github.com/eaze/tide-sqlx
> docs: add tide-sqlx to readme

- .github/CONTRIBUTING.md
This section was removed in 739736ea6c7c58f0faac75cdfaef20f12f73c4a4.
> Remove Developer Certificate of Origin link

- README.md
Hi All, this pr just add a new example app with `sqlx + tera`.
Thanks!
> add tide-basic-crud example app

- README.md
Add broker application to examples
> Add broker to example apps

- Cargo.toml
- src/request.rs
The Tide counterpart of https://github.com/http-rs/http-types/pull/333
> Request: allow Deserialize<'de> for .query() 

- src/redirect.rs
- src/request.rs
- src/response.rs
- src/response_builder.rs
issue #821
ps: I am not really sure if that's the correct way to link my code 😄.
> fixes #821: remove #[allow[clippy::from_over_into] and change to From

- src/response.rs
- src/response_builder.rs
This is a counterpart to https://github.com/http-rs/surf/pull/302.
I was doing a coding exercise and realized that both `surf::RequestBuilder` and `tide::ResponseBuilder` didn't have body shorthand methods yet. This makes it so passing bodies to responses using `Response::builder` is easier to write. Thanks!
```rust
let data = &Ip { ip: "129.0.0.1".into() };
// before
let mut res = Response::builder(200).body(Body::from_json(data)?).build();
// after
let mut res = Response::builder(200).body_json(data)?.build();
```
> Add body shorthands to `Response` and `ResponseBuilder`

- README.md
Hey, you said no contribution is too small! Anyway, it was bothering me, and I was like, hey, this is a great first pr! If you like it the way it was, just let me know and I'll close the pr.
> Fix readme so the text isn't all wonky

- src/redirect.rs
- tests/test_utils.rs
Fixes https://github.com/http-rs/tide/issues/845. Thanks!
> fix infinite redirection recursion

- src/redirect.rs
Fix #884
Fix comment simply. from 301 to 308
> Fix comment Redirect::permanent

- README.md
async-sqlx-session also supports mysql and ready for further support on database engines
> further async-sqlx-session support

- README.md
- src/lib.rs
Closes https://github.com/http-rs/tide/pull/828, https://github.com/http-rs/tide/issues/825. Ref https://github.com/http-rs/tide/discussions/866. Thanks!
> Fix the "hello world" example

- README.md
- src/lib.rs
The code was fixed in https://github.com/http-rs/tide/pull/868/, but the sample output is still incorrect.
> Fix the sample output in the README example

- README.md
* Implements a basic cookie store for temporary flash messages with request and response extensions
> Add tide-flash message middleware to readme

- src/lib.rs
- tests/cookies.rs
- tests/params.rs
- tests/unix.rs
Hope it makes sense.
I've followed the Issue discussion. It seemed fairly straightforward so I did the leg work ;)
> Fix #831 Expose Method from http_types.
